import {
  pythonModuleDirectory,
  pythonPyprojectToml,
  pythonReadme,
  pythonSampleModule,
  pythonSampleTest,
} from './python-project.algorithm'

describe('pythonModuleDirectory', () => {
  it('replaces hyphens with underscores', () => {
    expect(pythonModuleDirectory('my-svc')).toBe('my_svc')
  })

  it('replaces dots too — a dot is Python’s package separator', () => {
    // The subtle one. A hyphen is merely an invalid identifier character, but a
    // surviving dot would be *valid syntax* meaning something else entirely: a
    // submodule of a package that does not exist. That lands as a wrong
    // hatchling `packages` entry and an unimportable wheel, with no error at
    // generation time — so this is the case worth pinning down.
    expect(pythonModuleDirectory('my.svc')).toBe('my_svc')
    expect(pythonModuleDirectory('api.v2')).toBe('api_v2')
    expect(pythonModuleDirectory('my-svc.v2')).toBe('my_svc_v2')
  })

  it('leaves a name with no hyphens or dots unchanged', () => {
    expect(pythonModuleDirectory('pycore')).toBe('pycore')
  })
})

describe('pythonPyprojectToml', () => {
  it('writes the project name, hatchling backend and wheel packages list', () => {
    const toml = pythonPyprojectToml('my-svc', 'my_svc')
    expect(toml).toContain('name = "my-svc"')
    expect(toml).toContain('build-backend = "hatchling.build"')
    expect(toml).toContain('packages = ["my_svc"]')
    expect(toml).toContain('dependencies = []')
  })

  it('configures mypy as strict, so a generated project is typed from day one', () => {
    /*
     * Measured, not aspirational: both templates this generator writes are
     * fully annotated, so a freshly generated project passes `mypy --strict`
     * with no findings. Verified by running the real binary against the real
     * emitted manifest.
     */
    const toml = pythonPyprojectToml('my-svc', 'my_svc')

    expect(toml).toContain('[tool.mypy]')
    expect(toml).toContain('strict = true')
  })

  it('tolerates a stub-less third-party import, and ONLY that', () => {
    /*
     * The one thing that breaks plain strict in practice: importing a library
     * that ships no type stubs fails as `import-untyped` on code the user
     * wrote normally and cannot fix - the same class as the jsx-a11y and TOML
     * relaxations elsewhere in mnci, where a generated project must not fail
     * its own gate on upstream boilerplate.
     *
     * Asserted in BOTH directions. `import-not-found` - a module that
     * genuinely cannot be resolved - must keep failing, or the relaxation
     * would quietly turn every typo'd import into `Any`.
     */
    const toml = pythonPyprojectToml('my-svc', 'my_svc')

    expect(toml).toContain('disable_error_code = ["import-untyped"]')
    expect(toml).not.toContain('ignore_missing_imports')
    expect(toml).not.toContain('import-not-found"]')
  })
})

describe('pythonPyprojectToml: the metadata a published wheel carries', () => {
  /*
   * Every assertion here was a defect, and none of them was caught by anything:
   * before these tests the whole suite passed while a built `python-lib` wheel
   * carried a blank summary, no long description, and a version claiming a
   * stable API. Measured on a real generated workspace, wheel inspected.
   */

  it('starts at 0.0.1, the same as npm-lib, not 1.0.0', () => {
    /*
     * `1.0.0` is a semver claim that the public API is stable, made by a
     * generator on a package that has never been released - and `mnci add
     * npm-lib` has always written `0.0.1`, so it was inconsistent as well as
     * wrong.
     *
     * It compounds. `nx release`'s `fallbackCurrentVersionResolver` is `disk`,
     * so a first release with no tag reads THIS line and bumps from it: the
     * debut publish of a Python package came out as 1.0.1 or 1.1.0.
     */
    expect(pythonPyprojectToml('my-svc', 'my_svc')).toContain('version = "0.0.1"')
  })

  it('writes a real summary, because an empty one is worse than none', () => {
    // `description = ""` is not an absent field. It is a positive assertion of
    // nothing, and PyPI renders it as a blank summary on the project page.
    const toml = pythonPyprojectToml('my-svc', 'my_svc')

    expect(toml).not.toContain('description = ""')
    expect(toml).toContain('description = "my-svc, a Python package generated by MoNecromanCI."')
  })

  it('declares the readme, which is what makes a README become the long description', () => {
    /*
     * The subtle one. Without this key hatchling writes no long description
     * even when a README.md sits next to the manifest - so a user who noticed
     * the bare PyPI page and added a README would find it changed nothing.
     */
    expect(pythonPyprojectToml('my-svc', 'my_svc')).toContain('readme = "README.md"')
  })

  it('requires the Python mnci actually provisions, not an untested older one', () => {
    /*
     * `>=3.9` claimed support for three versions nothing anywhere tested: the
     * generated devcontainer pins 3.12 and the generated CI uses the runner's
     * own `python3`. Narrow and honest beats wide and unverified.
     *
     * The direction matters too. Widening later is additive and safe; narrowing
     * later breaks every consumer who took the first claim at face value.
     */
    const toml = pythonPyprojectToml('my-svc', 'my_svc')

    expect(toml).toContain('requires-python = ">=3.12"')
    expect(toml).not.toContain('>=3.9')
  })

  it('invents no licence, author or classifiers', () => {
    /*
     * Asserted so the fix above is not mistaken for "fill in all the metadata".
     * A generator cannot know an author or choose a licence, and guessing
     * either is worse than leaving a blank the author fills in deliberately -
     * `mnci add npm-lib` invents none of them either, and that symmetry is the
     * point. The bug was the ASYMMETRY, not the absence.
     */
    const toml = pythonPyprojectToml('my-svc', 'my_svc')

    expect(toml).not.toContain('license')
    expect(toml).not.toContain('authors')
    expect(toml).not.toContain('classifiers')
    expect(toml).not.toContain('[project.urls]')
  })
})

describe('pythonReadme', () => {
  it('is written at all, which is the finding', () => {
    // `mnci add npm-lib` has always written a README; the Python kinds never
    // did. A published Python package therefore looked bare next to its npm
    // sibling for no reason anyone chose.
    const readme = pythonReadme('my-svc', 'my_svc')

    expect(readme).toContain('# my-svc')
    expect(readme).toContain('Generated by [MoNecromanCI]')
  })

  it('names the file that `readme = "README.md"` points at', () => {
    // The two have to agree or the long description silently stays empty.
    expect(pythonPyprojectToml('my-svc', 'my_svc')).toContain('readme = "README.md"')
  })

  it('shows the IMPORT name, which is not always the project name', () => {
    // Python identifiers cannot contain a hyphen or a dot, so `my-svc` imports
    // as `my_svc`. A reader who only saw the project name would write the
    // wrong import, and this is the first place they look.
    const readme = pythonReadme('my-svc', 'my_svc')

    expect(readme).toContain('from my_svc import hello')
  })

  it('documents every target the project actually has', () => {
    // Parallel to the npm README rather than richer. The commands differ
    // because the toolchain does - Ruff and mypy have no npm equivalent here -
    // but a workspace holding both kinds should not look like it was generated
    // by two different tools.
    const readme = pythonReadme('my-svc', 'my_svc')

    for (const target of ['nx build my-svc', 'nx test my-svc', 'nx lint my-svc', 'nx typecheck my-svc'])
      expect(readme).toContain(target)
  })
})

describe('pythonSampleModule + pythonSampleTest', () => {
  it('generates a module and a test that actually pass together', () => {
    const module_ = pythonSampleModule('pycore')
    const test = pythonSampleTest('pycore')
    expect(module_).toContain('return "hello from pycore"')
    expect(test).toContain('from pycore import hello')
    expect(test).toContain('hello() == "hello from pycore"')
  })
})
