/**
 * A Python project's module directory name, derived from its Nx project name.
 *
 * @remarks
 * Python identifiers cannot contain hyphens, so `my-svc` becomes `my_svc`.
 *
 * Dots are mapped the same way, and that is not cosmetic: a dot is Python's
 * **package separator**, so leaving `my.svc` alone would name a submodule `svc`
 * of a package `my` that does not exist — producing a wrong
 * `[tool.hatch.build.targets.wheel] packages` entry and an unimportable wheel.
 * Unlike the Dart side, where pub rejects the name outright and fails loudly,
 * this one would fail quietly, which is why it is handled here rather than left
 * to the caller.
 *
 * @param name - The Nx project name.
 * @returns The module directory's basename (e.g. `my_svc`).
 * @throws Never - pure string mapping.
 * @typeParam None - this function has no generic type parameters.
 */
export function pythonModuleDirectory (name: string): string {
  return name.replaceAll(/[-.]/g, '_')
}

/**
 * The `pyproject.toml` written for a buildable Python project (app or lib).
 *
 * @remarks
 * `[tool.mypy]` is `strict`, and that is measured rather than aspirational:
 * the sample module and test this generator writes are both fully annotated,
 * so a freshly generated project passes `mypy --strict` with no findings. The
 * single relaxation is explained beside it.
 *
 * `hatchling` is the PEP 517 backend. The wheel target's `packages` list is
 * explicit (not hatchling's own auto-detection) because the `build` executor
 * patches this exact list when vendoring an internal-lib's module into the
 * wheel (see `parseVendorEntries`). `dependencies` starts empty — external
 * and vendored dependencies alike are wired by hand after generation; no
 * generator wires cross-project Python dependencies automatically.
 *
 * THE METADATA A PUBLISHED WHEEL ACTUALLY CARRIES
 *
 * Four of these lines were wrong, and every one of them was measured on a
 * published package rather than reasoned about. A `python-lib` built and
 * inspected produced a wheel whose entire metadata was its name, its version
 * and its dependencies: no summary, no long description, and a version that
 * claimed a stable API.
 *
 * - `version` is `0.0.1`, not `1.0.0`. `mnci add npm-lib` has always
 *   scaffolded `0.0.1`, and Python starting at `1.0.0` was both inconsistent
 *   and a semver claim nobody made — `1.0.0` says "this API is stable". It
 *   compounds: `nx release`'s `fallbackCurrentVersionResolver` is `disk`, so an
 *   untagged first release reads this line and bumps from it, publishing
 *   `1.0.1` or `1.1.0` as a debut.
 * - `description` is a real sentence rather than `""`. An empty string is not
 *   an absent field; it is a positive assertion of nothing, and PyPI renders it
 *   as a blank summary.
 * - `readme` is declared, which is the subtle one. Without this key hatchling
 *   writes no long description **even when a README exists**, so adding one by
 *   hand does not fix the bare project page. {@link pythonReadme} writes the
 *   file this points at, mirroring what `npm-lib` already got.
 * - `requires-python` is `>=3.12`, the version mnci actually provisions — the
 *   devcontainer pins it and the generated CI uses the runner's `python3`.
 *   Nothing anywhere tested 3.9, 3.10 or 3.11, so `>=3.9` was an untested
 *   claim. Narrow and honest beats wide and unverified; an author who does test
 *   older versions can widen it deliberately, which is the safe direction to
 *   move in (widening is additive, narrowing later breaks consumers).
 *
 * Still absent, on purpose: `license`, `authors`, `classifiers` and
 * `[project.urls]`. A generator cannot know an author or choose a licence, and
 * guessing either would be worse than leaving the author to fill it in —
 * `mnci add npm-lib` does not invent them either, and the asymmetry above was
 * the actual bug.
 *
 * @param name - The project name.
 * @param moduleDirectory - The project's module directory basename.
 * @returns The `pyproject.toml` contents.
 * @throws Never - pure string build.
 * @typeParam None - this function has no generic type parameters.
 */
export function pythonPyprojectToml (name: string, moduleDirectory: string): string {
  return `[project]
name = "${name}"
version = "0.0.1"
description = "${name}, a Python package generated by MoNecromanCI."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["${moduleDirectory}"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.mypy]
strict = true
# Stub-less third-party packages, and ONLY those. Measured on a generated
# project: plain strict passes out of the box, and the one thing that breaks it
# in practice is importing a library that ships no type stubs - "import yaml"
# fails as import-untyped on code you wrote normally and cannot fix. Disabling
# that one code keeps every other strict check on your own code, and a module
# that genuinely cannot be found still fails, as import-not-found.
disable_error_code = ["import-untyped"]
`
}

/**
 * The `README.md` a generated Python project gets, and its long description.
 *
 * @remarks
 * Two jobs, and the second is the one that was missing. It is the file a reader
 * opens, and it is what `readme = "README.md"` in the `pyproject.toml` points
 * at — so without it a published wheel has no long description at all and the
 * PyPI project page is a title and a `pip install` line.
 *
 * `mnci add npm-lib` has always written a README (`writeProjectReadme` in the
 * CLI); the Python kinds never did. That asymmetry is the whole finding: a
 * published Python package looked bare next to its npm sibling for no reason
 * anyone chose.
 *
 * Deliberately parallel to the npm one rather than richer. The commands differ
 * because the toolchain does — Ruff and mypy have no npm equivalent here — but
 * the shape is the same, so a workspace holding both does not look like it was
 * generated by two different tools.
 *
 * @param name - The project name, which is also the heading.
 * @param moduleDirectory - The importable module name, which is not always the
 * project name: Python identifiers cannot contain a hyphen or a dot, so
 * `my-svc` imports as `my_svc` and a reader needs telling.
 * @returns The `README.md` contents.
 * @throws Never - pure string build.
 * @typeParam None - this function has no generic type parameters.
 */
export function pythonReadme (name: string, moduleDirectory: string): string {
  return [
    `# ${name}`,
    '',
    'Generated by [MoNecromanCI](https://github.com/russoedu/MoNecromanCi).',
    '',
    '```python',
    `from ${moduleDirectory} import hello`,
    '```',
    '',
    '## Building',
    '',
    `Run \`nx build ${name}\` to build the wheel and the sdist into \`dist/\`.`,
    '',
    '## Running unit tests',
    '',
    `Run \`nx test ${name}\` to execute the unit tests via [pytest](https://pytest.org).`,
    '',
    '## Linting and type checking',
    '',
    `Run \`nx lint ${name}\` for [Ruff](https://docs.astral.sh/ruff/) and`,
    `\`nx typecheck ${name}\` for [mypy](https://mypy-lang.org) in strict mode.`,
    '',
  ].join('\n')
}

/**
 * A sample pure function written into a generated Python project's module.
 *
 * @remarks
 * Gives every generated project a genuinely testable unit out of the box —
 * paired with {@link pythonSampleTest}.
 *
 * @param moduleDirectory - The project's module directory basename.
 * @returns The `<module>/__init__.py` contents.
 * @throws Never - pure string build.
 * @typeParam None - this function has no generic type parameters.
 */
export function pythonSampleModule (moduleDirectory: string): string {
  return `def hello() -> str:
    return "hello from ${moduleDirectory}"
`
}

/**
 * The sample pytest proving a generated Python project's `test` target runs.
 *
 * @remarks
 * Imports {@link pythonSampleModule}'s function, so a fresh project's `test`
 * target is green out of the box, no wiring needed.
 *
 * @param moduleDirectory - The project's module directory basename.
 * @returns The `tests/test_<module>.py` contents.
 * @throws Never - pure string build.
 * @typeParam None - this function has no generic type parameters.
 */
export function pythonSampleTest (moduleDirectory: string): string {
  return `from ${moduleDirectory} import hello


def test_hello() -> None:
    assert hello() == "hello from ${moduleDirectory}"
`
}
