/** Shared Jest preset — generated by MoNecromanCI. Re-sync with 'monecromanci doctor'. */
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))

export function createConfig (projectName) {
  return {
    displayName:        projectName,
    testEnvironment:    'node',
    rootDir:            '.',
    roots:              ['<rootDir>/src'],
    setupFilesAfterEnv: [
      join(here, 'jest.setup.mjs'),
      join(here, 'jest.clear.mjs'),
    ],
    transform: {
      '^.+\\.[tj]sx?$': ['ts-jest', { tsconfig: join(here, 'tsconfig.jest.json') }],
    },
    moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'mjs', 'cjs', 'json'],
    collectCoverageFrom:  [
      '<rootDir>/src/**/*.ts',
      '!<rootDir>/src/**/*.d.ts',
      '!<rootDir>/src/index.ts',
    ],
    coverageProvider:  'v8',
    coverageDirectory: './coverage',
    coverageReporters: ['text', 'cobertura', 'html', 'lcov'],
    reporters:         [
      'default',
      ['jest-junit', { outputDirectory: './coverage', outputName: 'test-results.xml' }],
    ],
  }
}
