/**
 * The canonical, self-contained ESLint flat config emitted into every monorepo.
 *
 * Standard style (no semicolons) via **neostandard** (flat-native, ESLint 9
 * compatible — unlike the legacy eslint-config-standard which pins ESLint 8),
 * layered with unicorn, React, Jest, JSON/JSONC/JSON5, YAML and Markdown.
 * Deliberately **non type-checked** to stay fast on large codebases.
 *
 * `String.raw` keeps regex backslashes intact in the generated file.
 */
export const ESLINT_CONFIG_MJS = String.raw`// Centralised ESLint flat config — generated by nx-magic. Re-sync with 'nx-magic doctor'.
// Standard style (no semicolons) via neostandard + @stylistic + typescript-eslint,
// plus unicorn, React, Jest, JSON/JSONC/JSON5, YAML and Markdown.
// NON type-checked on purpose (fast on large codebases).
import markdown from '@eslint/markdown'
import pluginJest from 'eslint-plugin-jest'
import jsonc from 'eslint-plugin-jsonc'
import react from 'eslint-plugin-react'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import unicorn from 'eslint-plugin-unicorn'
import unusedImports from 'eslint-plugin-unused-imports'
import yaml from 'eslint-plugin-yml'
import globalsConfig from 'globals'
import neostandard from 'neostandard'

const code = ['**/*.{ts,mts,cts}', '**/*.{tsx,mtsx,ctsx}', '**/*.{js,mjs,cjs}', '**/*.{jsx,mjsx,cjsx}']
const tsx = ['**/*.{tsx,mtsx,ctsx}', '**/*.{jsx,mjsx,cjsx}']
const tests = [
  '**/*.{test,spec}.{ts,mts,cts}',
  '**/*.{test,spec}.{tsx,mtsx,ctsx}',
  '**/*.{test,spec}.{js,mjs,cjs}',
  '**/*.{test,spec}.{jsx,mjsx,cjsx}',
]

// @stylistic and @typescript-eslint plugins are registered by neostandard; their
// rules resolve here because flat config merges plugins per matched file.
const projectRules = {
  semi:                                  ['error', 'never'],
  '@stylistic/comma-dangle':             ['error', 'always-multiline'],
  '@stylistic/key-spacing':              ['error', { align: { beforeColon: false, afterColon: true, on: 'value' } }],
  '@stylistic/jsx-quotes':               ['error', 'prefer-single'],
  '@typescript-eslint/no-explicit-any':  'off',
  '@typescript-eslint/no-non-null-assertion': 'off',
  '@typescript-eslint/no-unused-vars':   'off',
  'unused-imports/no-unused-imports':    'error',
  'unused-imports/no-unused-vars':       ['warn', { vars: 'all', args: 'after-used', varsIgnorePattern: '^_', argsIgnorePattern: '^_' }],
  'unicorn/no-null':                     'off',
  'unicorn/prefer-top-level-await':      'off',
  'unicorn/prefer-module':               'off',
  'unicorn/prevent-abbreviations':       ['error', {
    ignore:                   [/err/i, /dev/i, /db/i, /(pre)?(pro?d)/i, /conf(ig)?/i, /env/i, /dist/i, /req/i, /res/i, /lib/i, /vars?/i, /Props/],
    checkShorthandProperties: false,
  }],
  'unicorn/filename-case': ['error', { cases: { camelCase: true, pascalCase: true }, ignore: [/^_.+\.[jt]s$/] }],
}

const testRules = {
  '@typescript-eslint/no-require-imports': 'off',
  '@typescript-eslint/no-empty-function':  'off',
  'unicorn/consistent-function-scoping':   'off',
  'no-new':                                'off',
}

export default [
  {
    ignores: [
      '.nx/*', 'coverage/*', 'dist/*', 'dist-dev/*', 'dist-uat/*', 'dist-prod/*',
      'doc/*', 'lib/*', 'node_modules/**', '**/node_modules', 'tmp/*',
      '.azurite/**', 'package-lock.json',
      // Tool-owned scripts are regenerated by nx-magic and exempt from the style gate.
      '.build-templates/**', 'tools/**',
    ],
  },

  // Standard style (no semicolons) + @stylistic + typescript-eslint (non type-checked).
  ...neostandard({ ts: true }),

  // Unicorn for all TS/JS.
  { ...unicorn.configs.recommended, files: code },

  // Project rule tweaks + unused-imports.
  {
    files:           code,
    plugins:         { 'unused-imports': unusedImports },
    languageOptions: { globals: { ...globalsConfig.node, ...globalsConfig.browser } },
    rules:           projectRules,
  },

  // React (tsx/jsx) — declared explicitly to avoid plugin-config shape drift.
  {
    files:    tsx,
    plugins:  { react },
    settings: { react: { version: 'detect' } },
    rules:    {
      'react/react-in-jsx-scope': 'off',
      'react/jsx-uses-react':     'error',
      'react/jsx-uses-vars':      'error',
    },
  },
  {
    files:   tsx,
    plugins: { 'react-hooks': reactHooks },
    rules:   { 'react-hooks/rules-of-hooks': 'error', 'react-hooks/exhaustive-deps': 'off' },
  },
  {
    files:   tsx,
    plugins: { 'react-refresh': reactRefresh },
    rules:   { 'react-refresh/only-export-components': ['warn', { allowConstantExport: true }] },
  },

  // Jest tests.
  {
    files:           tests,
    plugins:         { jest: pluginJest },
    languageOptions: { globals: { ...globalsConfig.jest } },
    rules:           testRules,
  },

  // JSON / JSONC / JSON5.
  ...jsonc.configs['flat/recommended-with-json'],
  ...jsonc.configs['flat/recommended-with-jsonc'],
  ...jsonc.configs['flat/recommended-with-json5'],

  // YAML.
  ...yaml.configs['flat/standard'],

  // Markdown.
  { files: ['**/*.md'], plugins: { markdown }, language: 'markdown/gfm' },
]
`
