/**
 * The rules oxlint does **not** implement, run through the real ESLint plugin.
 *
 * @remarks
 * This is what makes the parity claim honest rather than aspirational. Measured
 * against `@mnci/eslint-config`: of the 452 rules it enables for a project
 * `.ts`, oxlint implements 206 natively and **246 do not exist in it** — 169
 * `unicorn` and 56 `regexp` between them, which is the overwhelming majority.
 * Approximating those with oxlint's partial native `unicorn` set would have
 * meant silently dropping 169 rules.
 *
 * oxlint's `jsPlugins` loads a real ESLint plugin instead, so these rules are
 * not reimplementations — they are `eslint-plugin-unicorn` and
 * `eslint-plugin-regexp` themselves, at the **same versions**
 * `@mnci/eslint-config` depends on, which is why they are this package's own
 * dependencies rather than peers.
 *
 * oxlint's native `unicorn` plugin is deliberately left **off** (see
 * `index.js`): running both would report one defect twice under two different
 * rule names, the same reasoning that switches off `@eslint-react`'s duplicated
 * hooks rules in the ESLint config. `unicorn-js` is therefore an alias — oxlint
 * requires one when a JS plugin shares a built-in's name.
 *
 * Three costs, stated rather than buried:
 *
 * - **The bridge is alpha and explicitly not semver-stable**, per oxlint's own
 *   docs. `divergences.js` records what that has cost so far.
 * - **It boots Node and loads the plugins**, so it is not free: measured at
 *   ~2.1s versus ~0.07s for the native path alone on this repo's CLI source.
 *   Still roughly 3x faster than the ESLint run it replaces, but the "instant"
 *   framing stops being true.
 * - **`regexp` needs no alias** because oxlint has no built-in of that name;
 *   if it ever gains one, this must become an alias too or the names collide.
 */
export default {
  'regexp/confusing-quantifier': 'error',
  'regexp/control-character-escape': 'error',
  'regexp/match-any': 'error',
  'regexp/negation': 'error',
  'regexp/no-contradiction-with-assertion': 'error',
  'regexp/no-dupe-characters-character-class': 'error',
  'regexp/no-dupe-disjunctions': 'error',
  'regexp/no-empty-alternative': 'error',
  'regexp/no-empty-capturing-group': 'error',
  'regexp/no-empty-character-class': 'error',
  'regexp/no-empty-group': 'error',
  'regexp/no-empty-lookarounds-assertion': 'error',
  'regexp/no-empty-string-literal': 'error',
  'regexp/no-escape-backspace': 'error',
  'regexp/no-extra-lookaround-assertions': 'error',
  'regexp/no-invalid-regexp': 'error',
  'regexp/no-invisible-character': 'error',
  'regexp/no-lazy-ends': 'error',
  'regexp/no-misleading-capturing-group': 'error',
  'regexp/no-misleading-unicode-character': 'error',
  'regexp/no-non-standard-flag': 'error',
  'regexp/no-obscure-range': 'error',
  'regexp/no-optional-assertion': 'error',
  'regexp/no-potentially-useless-backreference': 'error',
  'regexp/no-super-linear-backtracking': 'error',
  'regexp/no-trivially-nested-assertion': 'error',
  'regexp/no-trivially-nested-quantifier': 'error',
  'regexp/no-unused-capturing-group': 'error',
  'regexp/no-useless-assertions': 'error',
  'regexp/no-useless-backreference': 'error',
  'regexp/no-useless-character-class': 'error',
  'regexp/no-useless-escape': 'error',
  'regexp/no-useless-lazy': 'error',
  'regexp/no-useless-non-capturing-group': 'error',
  'regexp/no-useless-quantifier': 'error',
  'regexp/no-useless-range': 'error',
  'regexp/no-useless-set-operand': 'error',
  'regexp/no-useless-string-literal': 'error',
  'regexp/no-useless-two-nums-quantifier': 'error',
  'regexp/no-zero-quantifier': 'error',
  'regexp/optimal-lookaround-quantifier': 'error',
  'regexp/optimal-quantifier-concatenation': 'error',
  'regexp/prefer-character-class': 'error',
  'regexp/prefer-d': 'error',
  'regexp/prefer-plus-quantifier': 'error',
  'regexp/prefer-predefined-assertion': 'error',
  'regexp/prefer-question-quantifier': 'error',
  'regexp/prefer-range': 'error',
  'regexp/prefer-set-operation': 'error',
  'regexp/prefer-star-quantifier': 'error',
  'regexp/prefer-unicode-codepoint-escapes': 'error',
  'regexp/prefer-w': 'error',
  'regexp/simplify-set-operations': 'error',
  'regexp/sort-flags': 'error',
  'regexp/strict': 'error',
  'regexp/use-ignore-case': 'error',
  'unicorn-js/better-dom-traversing': 'error',
  'unicorn-js/catch-error-name': ['error', { name: 'error', ignore: [] }],
  'unicorn-js/class-reference-in-static-methods': [
    'error',
    { preferThis: true, preferSuper: true }
  ],
  'unicorn-js/consistent-assert': 'error',
  'unicorn-js/consistent-class-member-order': [
    'error',
    {
      order: [
        'static-field',
        'static-block',
        'static-method',
        'private-field',
        'public-field',
        'constructor',
        'private-method',
        'public-method'
      ]
    }
  ],
  'unicorn-js/consistent-compound-words': ['error', {}],
  'unicorn-js/consistent-conditional-object-spread': ['error', 'logical'],
  'unicorn-js/consistent-date-clone': 'error',
  'unicorn-js/consistent-empty-array-spread': 'error',
  'unicorn-js/consistent-existence-index-check': 'error',
  'unicorn-js/consistent-export-decorator-position': ['error', 'above'],
  'unicorn-js/consistent-function-scoping': ['error', { checkArrowFunctions: true }],
  'unicorn-js/consistent-json-file-read': ['error', 'string'],
  'unicorn-js/consistent-optional-chaining': 'error',
  'unicorn-js/consistent-template-literal-escape': 'error',
  'unicorn-js/consistent-tuple-labels': 'error',
  'unicorn-js/default-export-style': ['error', { functions: 'inline', classes: 'inline' }],
  'unicorn-js/dom-node-dataset': ['error', { preferAttributes: false }],
  'unicorn-js/error-message': 'error',
  'unicorn-js/escape-case': ['error', 'uppercase'],
  'unicorn-js/expiring-todo-comments': [
    'error',
    {
      terms: ['todo', 'fixme', 'xxx'],
      ignore: [],
      checkDates: false,
      checkDatesOnPullRequests: false,
      allowWarningComments: true
    }
  ],
  'unicorn-js/explicit-length-check': ['error', { 'non-zero': 'greater-than' }],
  'unicorn-js/explicit-timer-delay': ['error', 'always'],
  'unicorn-js/isolated-functions': [
    'error',
    {
      functions: ['makeSynchronous', 'workerize'],
      selectors: [],
      comments: ['@isolated'],
      overrideGlobals: {}
    }
  ],
  'unicorn-js/logical-assignment-operators': ['error', 'always'],
  'unicorn-js/max-nested-calls': ['error', { max: 3 }],
  'unicorn-js/new-for-builtins': 'error',
  'unicorn-js/no-accessor-recursion': 'error',
  'unicorn-js/no-accidental-bitwise-operator': 'error',
  'unicorn-js/no-anonymous-default-export': 'error',
  'unicorn-js/no-array-callback-reference': ['error', { ignore: [] }],
  'unicorn-js/no-array-concat-in-loop': 'error',
  'unicorn-js/no-array-fill-with-reference-type': 'error',
  'unicorn-js/no-array-from-fill': 'error',
  'unicorn-js/no-array-method-this-argument': 'error',
  'unicorn-js/no-array-reverse': ['error', { allowExpressionStatement: true }],
  'unicorn-js/no-array-sort': ['error', { allowExpressionStatement: true }],
  'unicorn-js/no-array-sort-for-min-max': 'error',
  'unicorn-js/no-array-splice': 'error',
  'unicorn-js/no-async-promise-finally': 'error',
  'unicorn-js/no-await-expression-member': 'error',
  'unicorn-js/no-await-in-promise-methods': 'error',
  'unicorn-js/no-blob-to-file': 'error',
  'unicorn-js/no-boolean-sort-comparator': 'error',
  'unicorn-js/no-break-in-nested-loop': 'error',
  'unicorn-js/no-canvas-to-image': 'error',
  'unicorn-js/no-chained-comparison': 'error',
  'unicorn-js/no-collection-bracket-access': 'error',
  'unicorn-js/no-computed-property-existence-check': 'error',
  'unicorn-js/no-confusing-array-splice': 'error',
  'unicorn-js/no-confusing-array-with': 'error',
  'unicorn-js/no-console-spaces': 'error',
  'unicorn-js/no-constant-zero-expression': 'error',
  'unicorn-js/no-declarations-before-early-exit': 'error',
  'unicorn-js/no-document-cookie': 'error',
  'unicorn-js/no-double-comparison': 'error',
  'unicorn-js/no-duplicate-if-branches': 'error',
  'unicorn-js/no-duplicate-logical-operands': 'error',
  'unicorn-js/no-duplicate-loops': 'error',
  'unicorn-js/no-duplicate-set-values': 'error',
  'unicorn-js/no-empty-file': ['error', { allowComments: false }],
  'unicorn-js/no-error-property-assignment': 'error',
  'unicorn-js/no-exports-in-scripts': 'error',
  'unicorn-js/no-for-each': 'error',
  'unicorn-js/no-for-loop': 'error',
  'unicorn-js/no-global-object-property-assignment': 'error',
  'unicorn-js/no-immediate-mutation': 'error',
  'unicorn-js/no-impossible-length-comparison': 'error',
  'unicorn-js/no-incorrect-query-selector': 'error',
  'unicorn-js/no-instanceof-builtins': [
    'error',
    { useErrorIsError: false, strategy: 'loose', include: [], exclude: [] }
  ],
  'unicorn-js/no-invalid-argument-count': ['error', {}],
  'unicorn-js/no-invalid-character-comparison': 'error',
  'unicorn-js/no-invalid-fetch-options': 'error',
  'unicorn-js/no-invalid-remove-event-listener': 'error',
  'unicorn-js/no-invalid-well-known-symbol-methods': 'error',
  'unicorn-js/no-late-current-target-access': 'error',
  'unicorn-js/no-late-event-control': 'error',
  'unicorn-js/no-lonely-if': 'error',
  'unicorn-js/no-loop-iterable-mutation': 'error',
  'unicorn-js/no-magic-array-flat-depth': 'error',
  'unicorn-js/no-mismatched-map-key': 'error',
  'unicorn-js/no-misrefactored-assignment': 'error',
  'unicorn-js/no-multiple-promise-resolver-calls': 'error',
  'unicorn-js/no-named-default': 'error',
  'unicorn-js/no-negated-array-predicate': 'error',
  'unicorn-js/no-negated-comparison': ['error', { checkLogicalExpressions: false }],
  'unicorn-js/no-negated-condition': 'error',
  'unicorn-js/no-negation-in-equality-check': 'error',
  'unicorn-js/no-new-array': 'error',
  'unicorn-js/no-new-buffer': 'error',
  'unicorn-js/no-non-function-verb-prefix': [
    'error',
    { verbs: ['get', 'set', 'unset', 'delete', 'add', 'remove', 'destroy', 'create'], ignore: [] }
  ],
  'unicorn-js/no-nonstandard-builtin-properties': 'error',
  'unicorn-js/no-object-as-default-parameter': 'error',
  'unicorn-js/no-object-methods-with-collections': 'error',
  'unicorn-js/no-optional-chaining-on-undeclared-variable': 'error',
  'unicorn-js/no-process-exit': 'error',
  'unicorn-js/no-redundant-comparison': 'error',
  'unicorn-js/no-return-array-push': 'error',
  'unicorn-js/no-selector-as-dom-name': 'error',
  'unicorn-js/no-shorthand-property-overrides': 'error',
  'unicorn-js/no-single-promise-in-promise-methods': 'error',
  'unicorn-js/no-static-only-class': 'error',
  'unicorn-js/no-subtraction-comparison': 'error',
  'unicorn-js/no-thenable': 'error',
  'unicorn-js/no-this-assignment': 'error',
  'unicorn-js/no-this-outside-of-class': 'error',
  'unicorn-js/no-top-level-side-effects': 'error',
  'unicorn-js/no-transition-all': 'error',
  'unicorn-js/no-typeof-undefined': ['error', { checkGlobalVariables: false }],
  'unicorn-js/no-uncalled-method': 'error',
  'unicorn-js/no-undeclared-class-members': 'error',
  'unicorn-js/no-unnecessary-array-flat-depth': 'error',
  'unicorn-js/no-unnecessary-array-flat-map': 'error',
  'unicorn-js/no-unnecessary-array-splice-count': 'error',
  'unicorn-js/no-unnecessary-await': 'error',
  'unicorn-js/no-unnecessary-boolean-comparison': 'error',
  'unicorn-js/no-unnecessary-fetch-options': 'error',
  'unicorn-js/no-unnecessary-global-this': 'error',
  'unicorn-js/no-unnecessary-nested-ternary': 'error',
  'unicorn-js/no-unnecessary-polyfills': ['error', {}],
  'unicorn-js/no-unnecessary-slice-end': 'error',
  'unicorn-js/no-unnecessary-splice': 'error',
  'unicorn-js/no-unnecessary-string-trim': 'error',
  'unicorn-js/no-unreadable-array-destructuring': ['error', { maximumIgnoredElements: 1 }],
  'unicorn-js/no-unreadable-for-of-expression': 'error',
  'unicorn-js/no-unreadable-iife': 'error',
  'unicorn-js/no-unreadable-object-destructuring': 'error',
  'unicorn-js/no-unsafe-buffer-conversion': 'error',
  'unicorn-js/no-unsafe-promise-all-settled-values': 'error',
  'unicorn-js/no-unsafe-property-key': 'error',
  'unicorn-js/no-unsafe-string-replacement': 'error',
  'unicorn-js/no-unused-array-method-return': 'error',
  'unicorn-js/no-useless-boolean-cast': 'error',
  'unicorn-js/no-useless-coercion': 'error',
  'unicorn-js/no-useless-collection-argument': 'error',
  'unicorn-js/no-useless-compound-assignment': 'error',
  'unicorn-js/no-useless-concat': 'error',
  'unicorn-js/no-useless-continue': 'error',
  'unicorn-js/no-useless-delete-check': 'error',
  'unicorn-js/no-useless-else': 'error',
  'unicorn-js/no-useless-error-capture-stack-trace': 'error',
  'unicorn-js/no-useless-fallback-in-spread': 'error',
  'unicorn-js/no-useless-iterator-to-array': 'error',
  'unicorn-js/no-useless-length-check': 'error',
  'unicorn-js/no-useless-logical-operand': 'error',
  'unicorn-js/no-useless-override': 'error',
  'unicorn-js/no-useless-promise-resolve-reject': 'error',
  'unicorn-js/no-useless-re-export': 'error',
  'unicorn-js/no-useless-recursion': 'error',
  'unicorn-js/no-useless-spread': 'error',
  'unicorn-js/no-useless-switch-case': 'error',
  'unicorn-js/no-useless-template-literals': 'error',
  'unicorn-js/no-useless-undefined': [
    'error',
    { checkArguments: true, checkArrowFunctionBody: true }
  ],
  'unicorn-js/no-xor-as-exponentiation': 'error',
  'unicorn-js/no-zero-fractions': 'error',
  'unicorn-js/operator-assignment': ['error', 'always'],
  'unicorn-js/prefer-abort-signal-any': 'error',
  'unicorn-js/prefer-abort-signal-timeout': 'error',
  'unicorn-js/prefer-add-event-listener': ['error', { excludedPackages: ['koa', 'sax'] }],
  'unicorn-js/prefer-add-event-listener-options': 'error',
  'unicorn-js/prefer-aggregate-error': 'error',
  'unicorn-js/prefer-array-find': ['error', { checkFromLast: true }],
  'unicorn-js/prefer-array-flat': ['error', { functions: [] }],
  'unicorn-js/prefer-array-flat-map': 'error',
  'unicorn-js/prefer-array-from-async': 'error',
  'unicorn-js/prefer-array-from-map': 'error',
  'unicorn-js/prefer-array-from-range': 'error',
  'unicorn-js/prefer-array-index-of': 'error',
  'unicorn-js/prefer-array-iterable-methods': 'error',
  'unicorn-js/prefer-array-last-methods': 'error',
  'unicorn-js/prefer-array-slice': 'error',
  'unicorn-js/prefer-array-some': 'error',
  'unicorn-js/prefer-at': ['error', { getLastElementFunctions: [], checkAllIndexAccess: false }],
  'unicorn-js/prefer-await': 'error',
  'unicorn-js/prefer-bigint-literals': 'error',
  'unicorn-js/prefer-blob-reading-methods': 'error',
  'unicorn-js/prefer-block-statement-over-iife': 'error',
  'unicorn-js/prefer-boolean-return': 'error',
  'unicorn-js/prefer-class-fields': 'error',
  'unicorn-js/prefer-classlist-toggle': 'error',
  'unicorn-js/prefer-code-point': 'error',
  'unicorn-js/prefer-continue': ['error', { maximumStatements: 1 }],
  'unicorn-js/prefer-date-now': 'error',
  'unicorn-js/prefer-default-parameters': 'error',
  'unicorn-js/prefer-direct-iteration': 'error',
  'unicorn-js/prefer-dom-node-append': 'error',
  'unicorn-js/prefer-dom-node-html-methods': ['error', { checkGetHTML: true, checkSetHTML: false }],
  'unicorn-js/prefer-dom-node-remove': 'error',
  'unicorn-js/prefer-dom-node-replace-children': 'error',
  'unicorn-js/prefer-dom-node-text-content': 'error',
  'unicorn-js/prefer-early-return': ['error', { maximumStatements: 1 }],
  'unicorn-js/prefer-else-if': 'error',
  'unicorn-js/prefer-event-target': 'error',
  'unicorn-js/prefer-export-from': ['error', { checkUsedVariables: true }],
  'unicorn-js/prefer-flat-math-min-max': 'error',
  'unicorn-js/prefer-get-or-insert-computed': 'error',
  'unicorn-js/prefer-global-number-constants': 'error',
  'unicorn-js/prefer-global-this': 'error',
  'unicorn-js/prefer-group-by': 'error',
  'unicorn-js/prefer-has-check': 'error',
  'unicorn-js/prefer-hoisting-branch-code': 'error',
  'unicorn-js/prefer-https': 'error',
  'unicorn-js/prefer-identifier-import-export-specifiers': 'error',
  'unicorn-js/prefer-includes': 'error',
  'unicorn-js/prefer-includes-over-repeated-comparisons': ['error', { minimumComparisons: 3 }],
  'unicorn-js/prefer-iterable-in-constructor': 'error',
  'unicorn-js/prefer-iterator-helpers': 'error',
  'unicorn-js/prefer-iterator-to-array': 'error',
  'unicorn-js/prefer-iterator-to-array-at-end': 'error',
  'unicorn-js/prefer-keyboard-event-key': 'error',
  'unicorn-js/prefer-location-assign': 'error',
  'unicorn-js/prefer-logical-operator-over-ternary': 'error',
  'unicorn-js/prefer-map-from-entries': 'error',
  'unicorn-js/prefer-math-abs': 'error',
  'unicorn-js/prefer-math-constants': 'error',
  'unicorn-js/prefer-math-min-max': 'error',
  'unicorn-js/prefer-math-trunc': 'error',
  'unicorn-js/prefer-minimal-ternary': [
    'error',
    { checkVaryingBase: false, checkComputedMemberAccess: false }
  ],
  'unicorn-js/prefer-modern-dom-apis': 'error',
  'unicorn-js/prefer-modern-math-apis': 'error',
  'unicorn-js/prefer-native-coercion-functions': 'error',
  'unicorn-js/prefer-negative-index': 'error',
  'unicorn-js/prefer-node-protocol': 'error',
  'unicorn-js/prefer-number-coercion': 'error',
  'unicorn-js/prefer-number-is-safe-integer': 'error',
  'unicorn-js/prefer-number-properties': ['error', { checkInfinity: false, checkNaN: false }],
  'unicorn-js/prefer-object-define-properties': 'error',
  'unicorn-js/prefer-object-destructuring-defaults': 'error',
  'unicorn-js/prefer-object-from-entries': ['error', { functions: [] }],
  'unicorn-js/prefer-object-iterable-methods': 'error',
  'unicorn-js/prefer-observer-apis': 'error',
  'unicorn-js/prefer-optional-catch-binding': 'error',
  'unicorn-js/prefer-path2d': 'error',
  'unicorn-js/prefer-private-class-fields': 'error',
  'unicorn-js/prefer-promise-try': 'error',
  'unicorn-js/prefer-promise-with-resolvers': 'error',
  'unicorn-js/prefer-prototype-methods': 'error',
  'unicorn-js/prefer-queue-microtask': [
    'error',
    { checkSetImmediate: false, checkSetTimeout: false }
  ],
  'unicorn-js/prefer-reflect-apply': 'error',
  'unicorn-js/prefer-regexp-test': 'error',
  'unicorn-js/prefer-response-static-json': 'error',
  'unicorn-js/prefer-scoped-selector': 'error',
  'unicorn-js/prefer-set-has': ['error', { minimumItems: 0 }],
  'unicorn-js/prefer-set-methods': 'error',
  'unicorn-js/prefer-set-size': 'error',
  'unicorn-js/prefer-simple-condition-first': 'error',
  'unicorn-js/prefer-simple-sort-comparator': 'error',
  'unicorn-js/prefer-simplified-conditions': 'error',
  'unicorn-js/prefer-single-array-predicate': 'error',
  'unicorn-js/prefer-single-call': ['error', { ignore: [] }],
  'unicorn-js/prefer-single-object-destructuring': 'error',
  'unicorn-js/prefer-single-replace': 'error',
  'unicorn-js/prefer-smaller-scope': 'error',
  'unicorn-js/prefer-split-limit': 'error',
  'unicorn-js/prefer-spread': 'error',
  'unicorn-js/prefer-string-match-all': 'error',
  'unicorn-js/prefer-string-pad-start-end': 'error',
  'unicorn-js/prefer-string-raw': 'error',
  'unicorn-js/prefer-string-repeat': ['error', { minimumRepetitions: 3 }],
  'unicorn-js/prefer-string-replace-all': 'error',
  'unicorn-js/prefer-string-slice': 'error',
  'unicorn-js/prefer-string-starts-ends-with': 'error',
  'unicorn-js/prefer-string-trim-start-end': 'error',
  'unicorn-js/prefer-structured-clone': ['error', { functions: [] }],
  'unicorn-js/prefer-switch': [
    'error',
    { minimumCases: 3, emptyDefaultCase: 'no-default-comment' }
  ],
  'unicorn-js/prefer-ternary': ['error', 'always'],
  'unicorn-js/prefer-then-catch': 'error',
  'unicorn-js/prefer-toggle-attribute': 'error',
  'unicorn-js/prefer-type-error': 'error',
  'unicorn-js/prefer-type-literal-last': 'error',
  'unicorn-js/prefer-unary-minus': 'error',
  'unicorn-js/prefer-unicode-code-point-escapes': 'error',
  'unicorn-js/prefer-url-can-parse': 'error',
  'unicorn-js/prefer-url-href': 'error',
  'unicorn-js/prefer-url-search-parameters': 'error',
  'unicorn-js/prefer-while-loop-condition': 'error',
  'unicorn-js/relative-url-style': ['error', 'never'],
  'unicorn-js/require-array-join-separator': 'error',
  'unicorn-js/require-array-sort-compare': 'error',
  'unicorn-js/require-css-escape': ['error', { checkAllSelectors: false }],
  'unicorn-js/require-module-attributes': 'error',
  'unicorn-js/require-module-specifiers': 'error',
  'unicorn-js/require-number-to-fixed-digits-argument': 'error',
  'unicorn-js/require-passive-events': 'error',
  'unicorn-js/require-proxy-trap-boolean-return': 'error',
  'unicorn-js/switch-case-braces': ['error', 'always'],
  'unicorn-js/switch-case-break-position': 'error',
  'unicorn-js/text-encoding-identifier-case': ['error', { withDash: false }],
  'unicorn-js/throw-new-error': 'error'
}
