/**
 * Rules oxlint switches on by itself, which `@mnci/eslint-config` does not.
 *
 * @remarks
 * The unglamorous half of the parity promise, and the one that cannot be
 * skipped. oxlint enables a plugin's own rule set the moment the plugin is
 * listed — and enables `unicorn`, `typescript` and `oxc` even when they are
 * **not** listed, which is why entries for those appear here.
 *
 * Two attempts to avoid needing this file both failed, and are recorded so they
 * are not retried:
 *
 *  1. `categories: { correctness: 'error' }` was measured to report zero on this
 *     monorepo — with oxlint's DEFAULT plugins. Once `import`, `jest`, `vitest`,
 *     `react` and `jsx-a11y` were enabled it reported **8 findings across 6
 *     rules** on ESLint-clean source.
 *  2. Dropping to `categories: {}` changed nothing: the plugins, not the
 *     category, are what turn the rules on.
 *
 * So every rule oxlint enables that the ESLint config does not is listed here as
 * `off`. Some are genuinely useful (`oxc/const-comparisons` has no ESLint
 * equivalent at all) and switching them off still costs nothing that matters:
 * this package's contract is that a codebase passing `@mnci/eslint-config`
 * passes oxlint, and a rule ESLint never runs can only break that.
 *
 * Adding a rule to `@mnci/eslint-config` therefore means **removing** its entry
 * from here. `tests/parity.spec.ts` catches the case where that is forgotten in
 * the direction that matters; the reverse — a rule left enabled here that ESLint
 * does not run — is what the list itself prevents.
 *
 * Generated by diffing `oxlint --print-config` against the mirrored rule set,
 * not written by hand.
 */
export default {
  'constructor-super': 'off',
  'getter-return': 'off',
  'import/default': 'off',
  'import/namespace': 'off',
  'jest/expect-expect': 'off',
  'jest/no-conditional-expect': 'off',
  'jest/no-disabled-tests': 'off',
  'jest/no-export': 'off',
  'jest/no-standalone-expect': 'off',
  'jest/prefer-snapshot-hint': 'off',
  'jest/require-to-throw-message': 'off',
  'jest/valid-describe-callback': 'off',
  'jest/valid-expect-in-promise': 'off',
  'jest/valid-title': 'off',
  'jsx_a11y/control-has-associated-label': 'off',
  'jsx_a11y/lang': 'off',
  'jsx_a11y/no-aria-hidden-on-focusable': 'off',
  'jsx_a11y/prefer-tag-over-role': 'off',
  'no-caller': 'off',
  'no-class-assign': 'off',
  'no-const-assign': 'off',
  'no-dupe-class-members': 'off',
  'no-dupe-keys': 'off',
  'no-empty-character-class': 'off',
  'no-eval': 'off',
  'no-func-assign': 'off',
  'no-import-assign': 'off',
  'no-invalid-regexp': 'off',
  'no-iterator': 'off',
  'no-new-native-nonconstructor': 'off',
  'no-obj-calls': 'off',
  'no-setter-return': 'off',
  'no-this-before-super': 'off',
  'no-unreachable': 'off',
  'no-unsafe-negation': 'off',
  'no-unused-vars': 'off',
  'no-useless-backreference': 'off',
  'no-useless-rename': 'off',
  'no-with': 'off',
  'oxc/bad-array-method-on-arguments': 'off',
  'oxc/bad-char-at-comparison': 'off',
  'oxc/bad-comparison-sequence': 'off',
  'oxc/bad-match-all-arg': 'off',
  'oxc/bad-min-max-func': 'off',
  'oxc/bad-object-literal-comparison': 'off',
  'oxc/bad-replace-all-arg': 'off',
  'oxc/const-comparisons': 'off',
  'oxc/double-comparisons': 'off',
  'oxc/erasing-op': 'off',
  'oxc/missing-throw': 'off',
  'oxc/number-arg-out-of-range': 'off',
  'oxc/only-used-in-recursion': 'off',
  'oxc/uninvoked-array-callback': 'off',
  'promise/no-callback-in-promise': 'off',
  'react/forward-ref-uses-ref': 'off',
  'react/jsx-key': 'off',
  'react/jsx-no-duplicate-props': 'off',
  'react/jsx-no-undef': 'off',
  'react/jsx-props-no-spread-multi': 'off',
  'react/no-children-prop': 'off',
  'react/no-danger-with-children': 'off',
  'react/no-did-mount-set-state': 'off',
  'react/no-did-update-set-state': 'off',
  'react/no-find-dom-node': 'off',
  'react/no-is-mounted': 'off',
  'react/no-render-return-value': 'off',
  'react/no-string-refs': 'off',
  'react/no-this-in-sfc': 'off',
  'react/no-unsafe': 'off',
  'react/no-will-update-set-state': 'off',
  'react/void-dom-elements-no-children': 'off',
  'typescript/no-base-to-string': 'off',
  'typescript/no-meaningless-void-operator': 'off',
  'typescript/no-misused-spread': 'off',
  'typescript/no-redundant-type-constituents': 'off',
  'typescript/no-unnecessary-parameter-property-assignment': 'off',
  'typescript/no-unsafe-unary-minus': 'off',
  'typescript/no-useless-default-assignment': 'off',
  'typescript/no-useless-empty-export': 'off',
  'typescript/require-array-sort-compare': 'off',
  'typescript/restrict-template-expressions': 'off',
  'unicorn/no-await-in-promise-methods': 'off',
  'unicorn/no-empty-file': 'off',
  'unicorn/no-invalid-fetch-options': 'off',
  'unicorn/no-invalid-remove-event-listener': 'off',
  'unicorn/no-new-array': 'off',
  'unicorn/no-single-promise-in-promise-methods': 'off',
  'unicorn/no-thenable': 'off',
  'unicorn/no-unnecessary-await': 'off',
  'unicorn/no-useless-fallback-in-spread': 'off',
  'unicorn/no-useless-length-check': 'off',
  'unicorn/no-useless-spread': 'off',
  'unicorn/prefer-set-size': 'off',
  'unicorn/prefer-string-starts-ends-with': 'off',
  'vitest/expect-expect': 'off',
  'vitest/hoisted-apis-on-top': 'off',
  'vitest/no-conditional-expect': 'off',
  'vitest/no-conditional-tests': 'off',
  'vitest/no-disabled-tests': 'off',
  'vitest/no-focused-tests': 'off',
  'vitest/no-standalone-expect': 'off',
  'vitest/prefer-snapshot-hint': 'off',
  'vitest/require-awaited-expect-poll': 'off',
  'vitest/require-local-test-context-for-concurrent-snapshots': 'off',
  'vitest/require-mock-type-parameters': 'off',
  'vitest/require-to-throw-message': 'off',
  'vitest/valid-describe-callback': 'off',
  'vitest/valid-expect': 'off',
  'vitest/valid-expect-in-promise': 'off',
  'vitest/valid-title': 'off',
  'vitest/warn-todo': 'off'
}
