import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { GUIDE_FILE, syncGuide } from './guide'

let repoRoot: string

beforeEach(() => {
  repoRoot = mkdtempSync(join(tmpdir(), 'monecromanci-guide-'))
})

afterEach(() => {
  rmSync(repoRoot, { recursive: true, force: true })
})

describe('syncGuide', () => {
  it('writes the packaged guide to MoNecromanCi.md at the repo root', () => {
    syncGuide(repoRoot)

    const content = readFileSync(join(repoRoot, GUIDE_FILE), 'utf8')
    expect(content).toContain('# MoNecromanCI')
    expect(content).toContain('Tool-owned: regenerated by MoNecromanCI')
    expect(content).toContain('Conventional Commits')
  })

  it('overwrites an edited copy so the guide always matches the tool version', () => {
    writeFileSync(join(repoRoot, GUIDE_FILE), 'my own notes')

    syncGuide(repoRoot)

    expect(readFileSync(join(repoRoot, GUIDE_FILE), 'utf8')).not.toBe('my own notes')
  })
})
