import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import * as yaml from 'js-yaml'
import { githubActionsYaml, readMnciConfig } from './overlay'

/**
 * This repo's own CI must actually run the pipeline mnci ships.
 *
 * @remarks
 * mnci is dogfooded: `.github/workflows/ci.yml` here is an mnci-owned file,
 * generated by {@link githubActionsYaml}. Nothing checked that it stayed in step
 * with the generator, and the cost of that showed up twice in one day.
 *
 * `npm audit` was the expensive one. The generator has emitted an audit step for
 * a long time; this repo's workflow never had it. So a real `npm audit` reported
 * **9 vulnerabilities (8 high, 1 moderate)** that CI had never once mentioned —
 * including a `js-yaml` override pinned to a version the advisory had since been
 * extended to cover, which read as fixed and was not. Six further guards were
 * missing alongside it: pip-audit, all three Go steps and all three Flutter
 * steps.
 *
 * **Why this is one-directional.** A byte comparison is useless here, because the
 * two files legitimately differ and always will: this repo's workflow carries
 * `workflow_dispatch`, the nightly `schedule` and a whole `e2e-windows` job, none
 * of which the generator emits — a generated workspace has no e2e suite to run.
 * It also tracks newer action versions (`checkout@v7` vs `@v4`) through
 * Dependabot. Regenerating wholesale would delete the nightly, which is the one
 * thing that stops the e2e rotting unnoticed.
 *
 * So the invariant is the useful half: **every command the generator emits for
 * the `ci` job must be present here.** Extra steps are fine. Newer `uses:`
 * versions are fine, and fall out for free since only `run:` commands are
 * compared. A *missing* guard is not fine — that is CI here being weaker than
 * the CI mnci hands to its users.
 *
 * There is deliberately **no exemption table**. Every one of the seven missing
 * guards was added rather than excused: each begins with an existence check and
 * no-ops in a workspace without the relevant toolchain, so the cost of carrying
 * them is a few skipped steps, while the benefit is that a Go or Python project
 * landing in this repo is covered on the day it lands. A table of seven
 * "harmless" exemptions is how the audit step stayed missing.
 */

const repoRoot = join(__dirname, '..', '..', '..')

interface Step {
  name?: string
  run?: string
  uses?: string
}

interface Workflow {
  jobs: Record<string, { steps: Step[] }>
}

/**
 * The `run:` commands of one job, in order.
 *
 * @param workflow - A parsed workflow document.
 * @param job - The job id.
 * @returns Every `run` command in that job's steps.
 */
function runCommands(workflow: Workflow, job: string): string[] {
  return (workflow.jobs[job]?.steps ?? [])
    .filter((step): step is Step & { run: string } => typeof step.run === 'string')
    .map(step => step.run)
}

/**
 * The step name a command belongs to, for a readable failure message.
 *
 * @param workflow - A parsed workflow document.
 * @param job - The job id.
 * @param command - The `run` command to look up.
 * @returns The step's `name`, or the command's opening characters.
 */
function nameOf(workflow: Workflow, job: string, command: string): string {
  const step = (workflow.jobs[job]?.steps ?? []).find(candidate => candidate.run === command)

  return step?.name ?? command.slice(0, 60)
}

/**
 * The `uses:` entries of a workflow's `ci` job.
 *
 * @param workflow - A parsed workflow document.
 * @returns Every action reference in that job's steps.
 */
function usesOf(workflow: Workflow): string[] {
  return (workflow.jobs.ci?.steps ?? [])
    .map(step => step.uses)
    .filter((entry): entry is string => typeof entry === 'string')
}

const actual = yaml.load(
  readFileSync(join(repoRoot, '.github/workflows/ci.yml'), 'utf8')
) as Workflow

// Generated with this repo's own persisted options, so the comparison is against
// what `mnci upgrade` would write here — not against some default.
const persisted = readMnciConfig(repoRoot)
const generated = yaml.load(githubActionsYaml(persisted.agent ?? 'ubuntu-latest')) as Workflow

describe("this repo's ci.yml against the pipeline overlay.ts generates", () => {
  it('parsed both workflows and found a non-trivial number of steps', () => {
    // Without this the assertions below would pass just as happily on an empty
    // parse — the shape of gate that this whole file exists to prevent.
    expect(runCommands(generated, 'ci').length).toBeGreaterThan(10)
    expect(runCommands(actual, 'ci').length).toBeGreaterThan(10)
  })

  it('runs every guard the generator emits, with none missing', () => {
    // The assertion that would have caught the missing `npm audit` step, and with
    // it the nine advisories nothing reported. Compared by exact command text:
    // these are `node -e` one-liners shared verbatim between both CI providers,
    // so any edit to a guard in overlay.ts shows up here as a mismatch until this
    // repo is re-synced.
    const here = new Set(runCommands(actual, 'ci'))
    const missing = runCommands(generated, 'ci')
      .filter(command => !here.has(command))
      .map(command => nameOf(generated, 'ci', command))

    expect(missing).toEqual([])
  })

  it('keeps the extras that are the reason a byte comparison cannot be used', () => {
    // Asserted positively, so nobody "fixes" this drift by regenerating the file
    // and silently deleting the nightly schedule that keeps the e2e honest.
    const raw = readFileSync(join(repoRoot, '.github/workflows/ci.yml'), 'utf8')

    expect(raw).toContain('workflow_dispatch:')
    expect(raw).toContain('schedule:')
    expect(Object.keys(actual.jobs)).toContain('e2e-windows')
    // ...and the generator emits none of them, which is what makes them extras
    // rather than drift.
    expect(Object.keys(generated.jobs)).not.toContain('e2e-windows')
  })

  it('does not require the generated `uses:` versions, so Dependabot can bump them', () => {
    // `checkout@v7` here vs `@v4` from the generator is a Dependabot bump, not a
    // regression. Comparing only `run:` commands is what allows that, and this
    // pins the reasoning rather than leaving it implicit in the helper above.
    expect(usesOf(actual).some(entry => entry.startsWith('actions/checkout@'))).toBe(true)
    expect(usesOf(generated).some(entry => entry.startsWith('actions/checkout@'))).toBe(true)
  })
})
