import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import * as yaml from 'js-yaml'
import { ACTION_VERSIONS, DOTNET_SDK_VERSION, FLUTTER_SDK_VERSION, githubActionsYaml, nugetFeedUrl, pythonPublishUrl, readMnciConfig } from './workspace-overlay'

/**
 * This repo's own CI must actually run the pipeline mnci ships.
 *
 * @remarks
 * mnci is dogfooded: `.github/workflows/ci.yml` here is an mnci-owned file,
 * generated by {@link githubActionsYaml}. Nothing checked that it stayed in step
 * with the generator, and the cost of that showed up twice in one day.
 *
 * `npm audit` was the expensive one. The generator has emitted an audit step for
 * a long time; this repo's workflow never had it. So a real `npm audit` reported
 * **9 vulnerabilities (8 high, 1 moderate)** that CI had never once mentioned —
 * including a `js-yaml` override pinned to a version the advisory had since been
 * extended to cover, which read as fixed and was not. Six further guards were
 * missing alongside it: pip-audit, all three Go steps and all three Flutter
 * steps.
 *
 * **Why this is one-directional.** A byte comparison is useless here, because the
 * two files legitimately differ and always will: this repo's workflow carries
 * `workflow_dispatch`, the nightly `schedule` and a whole `e2e-windows` job, none
 * of which the generator emits — a generated workspace has no e2e suite to run.
 * Regenerating wholesale would delete the nightly, which is the one thing that
 * stops the e2e rotting unnoticed.
 *
 * So the invariant is the useful half: **every command the generator emits for
 * the `ci` job must be present here.** Extra steps are fine. A *missing* guard is
 * not fine — that is CI here being weaker than the CI mnci hands to its users.
 *
 * **`uses:` versions get a second, opposite check.** This file used to say newer
 * action versions here "fall out for free since only `run:` commands are
 * compared", and treat a version difference as a Dependabot bump rather than
 * drift. That is right about *this* repo — running `checkout@v7` against a
 * generator emitting `@v4` never makes CI here weaker, which is the invariant
 * above. It is wrong about users: nothing was watching the other direction, and
 * three of the four actions had gone three majors stale in the generator while
 * Dependabot kept this file current. `setup-dotnet` is the exception that proves
 * it — it matches only because PR #189 ported it by hand after someone noticed.
 *
 * So `ACTION_VERSIONS` is asserted to be at least as new as this workflow. The
 * cost is real and was the reason the old test existed: a Dependabot PR bumping
 * an action now goes red until the same PR bumps the constant. That is a
 * one-line edit, and it is the edit that was being silently skipped.
 *
 * There is deliberately **no exemption table**. Every one of the seven missing
 * guards was added rather than excused: each begins with an existence check and
 * no-ops in a workspace without the relevant toolchain, so the cost of carrying
 * them is a few skipped steps, while the benefit is that a Go or Python project
 * landing in this repo is covered on the day it lands. A table of seven
 * "harmless" exemptions is how the audit step stayed missing.
 */

const repoRoot = join(__dirname, '..', '..', '..')

interface Step {
  'name'?:              string
  'run'?:               string
  'uses'?:              string
  'if'?:                string
  'with'?:              Record<string, string>
  'continue-on-error'?: boolean
}

interface Workflow {
  jobs: Record<string, { steps: Step[] }>
}

/**
 * The `run:` commands of one job, in order.
 *
 * @param workflow - A parsed workflow document.
 * @param job - The job id.
 * @returns Every `run` command in that job's steps.
 */
function runCommands (workflow: Workflow, job: string): string[] {
  return (workflow.jobs[job]?.steps ?? [])
    .filter((step): step is Step & { run: string } => typeof step.run === 'string')
    .map(step => step.run)
}

/**
 * The step name a command belongs to, for a readable failure message.
 *
 * @param workflow - A parsed workflow document.
 * @param job - The job id.
 * @param command - The `run` command to look up.
 * @returns The step's `name`, or the command's opening characters.
 */
function nameOf (workflow: Workflow, job: string, command: string): string {
  const step = (workflow.jobs[job]?.steps ?? []).find(candidate => candidate.run === command)

  return step?.name ?? command.slice(0, 60)
}

/**
 * The `uses:` entries of a workflow's `ci` job.
 *
 * @param workflow - A parsed workflow document.
 * @returns Every action reference in that job's steps.
 */
function usesOf (workflow: Workflow): string[] {
  return (workflow.jobs.ci?.steps ?? [])
    .map(step => step.uses)
    .filter((entry): entry is string => typeof entry === 'string')
}

const actual = yaml.load(
  readFileSync(join(repoRoot, '.github/workflows/ci.yml'), 'utf8'),
) as Workflow

/*
 * Generated with this repo's own persisted options, so the comparison is
 * against what `mnci upgrade` would write HERE.
 *
 * Every argument matters, and for a while only the first was passed. This repo
 * persists `registry.kind: 'npm'`, while the parameter DEFAULTS to
 * 'azure-artifacts' - so the generated workflow being compared was one mnci
 * would never write here, and any step that exists only for the public-npm
 * registry was invisible to this test. Caught when an npm-only guard was added
 * and this file stayed green.
 */
const persisted = readMnciConfig(repoRoot)
const registry = persisted.registry ?? { kind: 'npm' as const }
const generated = yaml.load(githubActionsYaml(
  persisted.agent ?? 'ubuntu-latest',
  pythonPublishUrl(registry),
  registry.kind,
  persisted.ci === 'azure' ? 'both' : (persisted.ci ?? 'github'),
  nugetFeedUrl(registry),
)) as Workflow

describe("this repo's ci.yml against the pipeline overlay.ts generates", () => {
  it('parsed both workflows and found a non-trivial number of steps', () => {
    // Without this the assertions below would pass just as happily on an empty
    // parse — the shape of gate that this whole file exists to prevent.
    expect(runCommands(generated, 'ci').length).toBeGreaterThan(10)
    expect(runCommands(actual, 'ci').length).toBeGreaterThan(10)
  })

  it('runs every guard the generator emits, with none missing', () => {
    // The assertion that would have caught the missing `npm audit` step, and with
    // it the nine advisories nothing reported. Compared by exact command text:
    // these are `node -e` one-liners shared verbatim between both CI providers,
    // so any edit to a guard in overlay.ts shows up here as a mismatch until this
    // repo is re-synced.
    const here = new Set(runCommands(actual, 'ci'))
    const missing = runCommands(generated, 'ci')
      .filter(command => !here.has(command))
      .map(command => nameOf(generated, 'ci', command))

    expect(missing).toEqual([])
  })

  it('keeps the extras that are the reason a byte comparison cannot be used', () => {
    // Asserted positively, so nobody "fixes" this drift by regenerating the file
    // and silently deleting the nightly schedule that keeps the e2e honest.
    const raw = readFileSync(join(repoRoot, '.github/workflows/ci.yml'), 'utf8')

    expect(raw).toContain('workflow_dispatch:')
    expect(raw).toContain('schedule:')
    expect(Object.keys(actual.jobs)).toContain('e2e-windows')
    // ...and the generator emits none of them, which is what makes them extras
    // rather than drift.
    expect(Object.keys(generated.jobs)).not.toContain('e2e-windows')
  })

  it('pins action majors that are not behind the ones this repo runs', () => {
    // The direction the `run:`-only comparison cannot see. Dependabot keeps this
    // workflow current and cannot touch ACTION_VERSIONS, so without this the
    // generator hands users whatever majors were current when someone last
    // remembered — which had drifted to three behind.
    //
    // Only `actions/*` are compared, and only for actions the generator actually
    // emits: this repo's e2e-windows job is free to use anything it likes.
    // Collected into one array and asserted empty, rather than one expectation
    // per action: `toMatchObject` prints only the keys it matched on, so a
    // per-action assertion reports `atLeast: false` and nothing about WHICH
    // action or what to edit. An array comparison prints every field.
    const stale = Object.entries(ACTION_VERSIONS).flatMap(([action, generatedMajor]) => {
      const here = usesOf(actual)
        .filter(entry => entry.startsWith(`${action}@v`))
        .map(entry => Number(entry.slice(`${action}@v`.length).split('.', 1)[0]))

      if (here.length === 0 || Number(generatedMajor.slice(1)) >= Math.max(...here)) {
        return []
      }

      return [{
        action,
        generates:    generatedMajor,
        thisRepoRuns: `v${Math.max(...here)}`,
        remedy:       `bump ACTION_VERSIONS['${action}'] in overlay.use-case.ts`,
      }]
    })

    expect(stale).toEqual([])
  })
})

describe('the e2e job provisions the toolchains its own suite needs', () => {
  const steps = actual.jobs['e2e-windows']?.steps ?? []
  const names = steps.map(step => step.name ?? '')

  it('installs golangci-lint and the Flutter SDK', () => {
    // Both had been absent, and the consequence was not a failure but a silence:
    // the suite reported `SKIPPED the go lint assertion` and `SKIPPED the entire
    // Flutter section` on every run, so `@mnci/nx-flutter` — a first-party,
    // published plugin — had never once been exercised end to end.
    expect(names.some(name => name.includes('golangci-lint'))).toBe(true)
    expect(names.some(name => name.includes('Flutter SDK'))).toBe(true)
  })

  it('provisions them UNCONDITIONALLY, not through the marker-gated ci guards', () => {
    // The trap this exists for. Every Go/Flutter guard in the `ci` job begins with
    // `existsSync('go.mod')` / `existsSync('pubspec.yaml')` against the working
    // directory. This job's working directory is the repo itself, which has
    // neither — the e2e generates its workspaces in a temp directory. Copying the
    // `ci` job's steps here would therefore skip every time and look like it had
    // fixed something.
    const provisioning = steps.filter(step =>
      ['golangci-lint', 'Flutter SDK', 'Go tool bin'].some(marker =>
        (step.name ?? '').includes(marker),
      ),
    )

    expect(provisioning.length).toBeGreaterThan(0)
    for (const step of provisioning) {
      expect(step.run).not.toContain("existsSync('go.mod')")
      expect(step.run).not.toContain("existsSync('pubspec.yaml')")
    }
  })

  it('pins the same Flutter version overlay.ts ships, so the two cannot drift', () => {
    // The workflow hardcodes the version because this job is hand-maintained —
    // the generator emits no e2e job at all. That is a drift risk of exactly the
    // kind this file exists to catch, so it is caught here rather than introduced
    // and forgotten: bump FLUTTER_SDK_VERSION and this fails until the workflow
    // follows.
    const flutterSteps = steps.filter(step => (step.name ?? '').includes('Flutter'))

    expect(flutterSteps.length).toBeGreaterThan(0)
    for (const step of flutterSteps) {
      expect(step.run).toContain(FLUTTER_SDK_VERSION)
    }
  })

  it('lets a toolchain install fail without reddening the run', () => {
    // An SDK download is a network operation on someone else's infrastructure.
    // The e2e already reports an absent toolchain as a loud SKIPPED, so degrading
    // to that beats failing a nightly for something that is not mnci's fault —
    // and it cannot degrade silently, because the report names every skip.
    const networkSteps = steps.filter(candidate =>
      ['golangci-lint', 'Flutter SDK', 'PATH'].some(marker =>
        (candidate.name ?? '').includes(marker),
      ),
    )

    expect(networkSteps.length).toBeGreaterThan(0)
    for (const step of networkSteps) {
      expect((step as { 'continue-on-error'?: boolean })['continue-on-error']).toBe(true)
    }
  })

  it('installs the .NET SDK unconditionally too, pinned and non-reddening the same way', () => {
    // The C# analogue of the Go/Flutter checks above, adapted for a `uses:`
    // step: `actions/setup-dotnet` carries no `run:` to grep for a marker
    // check in, so "unconditionally" here means no `if:` gate at all — the
    // ci job's own install step is gated on hashFiles('**/*.csproj'), which
    // this job's working directory (this repo, not a generated workspace)
    // never satisfies.
    //
    // Matched by action name only, not a pinned major. The version question is
    // not this assertion's job — it belongs to the ACTION_VERSIONS check above,
    // which compares every action in one place and says which constant to edit.
    // Pinning a literal major here instead is what made the old arrangement
    // brittle for no gain: it re-broke on a bump that was not drift, while the
    // drift that mattered went unwatched.
    const dotnetStep = steps.find(step => step.uses?.startsWith('actions/setup-dotnet@'))

    expect(dotnetStep).toBeDefined()
    expect(dotnetStep?.if).toBeUndefined()
    expect(dotnetStep?.['continue-on-error']).toBe(true)
    // Pinned to the same constant overlay.ts ships, so bumping DOTNET_SDK_VERSION
    // fails this until the workflow follows — the same drift guard the Flutter
    // version check above already has.
    expect(dotnetStep?.with?.['dotnet-version']).toBe(DOTNET_SDK_VERSION)
  })
})
