/** Matches the top-level `version:` key of a pubspec (not a nested one). */
const VERSION_LINE = /^version:[ \t]*(\S+)[ \t]*$/m

/** Matches the top-level `resolution:` key. */
const RESOLUTION_LINE = /^resolution:[ \t]*\S+[ \t]*$/m

/**
 * Matches a whole top-level `environment:` block, including its indented body.
 *
 * @remarks
 * The `\r?` is load-bearing on Windows and was missing. `flutter create` writes
 * CRLF there, so the text is `environment:\r\n` — and a literal `\n` in the
 * pattern never matches it. The block was therefore never found, and
 * {@link withWorkspaceResolution} threw
 * "pubspec.yaml has no `environment:` block to anchor `resolution: workspace` to"
 * on a file `flutter create` had just written perfectly.
 *
 * Note the sibling patterns are unaffected: they end in `$`, and ECMAScript
 * counts `\r` as a line terminator, so `$` matches before it. Only a **literal**
 * `\n` is CRLF-sensitive, which is exactly why this one line broke and the
 * others did not.
 */
const ENVIRONMENT_BLOCK = /^environment:\r?\n(?:[ \t]+\S.*\r?\n)+/m

/**
 * Reads the top-level `version:` from a pubspec's text.
 *
 * @remarks
 * A regex rather than a YAML parser, for the same reason
 * `@mnci/nx-python-pip` reads `pyproject.toml`'s version line with one: the
 * only thing being read or written is a single scalar on its own line, and a
 * YAML dependency would have to round-trip the file without disturbing the
 * comments `flutter create` writes throughout it. `^...$` with the `m` flag
 * keeps this anchored to a *top-level* key, so the `version:` that can appear
 * nested under a dependency is never matched.
 *
 * @param contents - The pubspec.yaml text.
 * @returns The version string, or `undefined` when there is no top-level
 * `version:` key (valid for a Flutter app, which may omit it).
 * @throws Never - a missing key yields `undefined`.
 * @typeParam None - this function has no generic type parameters.
 */
export function readPubspecVersion (contents: string): string | undefined {
  return VERSION_LINE.exec(contents)?.[1]
}

/**
 * Returns the pubspec text with its top-level `version:` set to `version`.
 *
 * @remarks
 * Only rewrites an existing key — a pubspec with no `version:` is returned
 * unchanged rather than having one invented, so this can be called
 * unconditionally.
 *
 * @param contents - The pubspec.yaml text.
 * @param version - The version to write.
 * @returns The updated text.
 * @throws Never - pure string transformation.
 * @typeParam None - this function has no generic type parameters.
 */
export function writePubspecVersion (contents: string, version: string): string {
  // A function replacement, not a string: a literal would let a `$&`/`$1`
  // sequence in `version` be interpreted as a capture-group reference.
  return contents.replace(VERSION_LINE, () => `version: ${version}`)
}

/**
 * Returns the pubspec text with `resolution: workspace` present.
 *
 * @remarks
 * This one line is what makes a package a *member* of the root pub workspace
 * — without it `pub` resolves the package standalone, giving it its own
 * lockfile and defeating the whole central-dependency model. Inserted right
 * after the `environment:` block because that is where Dart's own workspace
 * documentation places it, and because `flutter create` always emits an
 * `environment:` block, making it a reliable anchor.
 *
 * Idempotent: a pubspec that already declares `resolution:` is returned
 * unchanged, so re-running a generator never duplicates the key.
 *
 * @param contents - The pubspec.yaml text.
 * @returns The updated text.
 * @throws Error when the pubspec has no `environment:` block to anchor to.
 * @typeParam None - this function has no generic type parameters.
 */
export function withWorkspaceResolution (contents: string): string {
  if (RESOLUTION_LINE.test(contents)) {
    return contents
  }
  if (!ENVIRONMENT_BLOCK.test(contents)) {
    throw new Error(
      'pubspec.yaml has no `environment:` block to anchor `resolution: workspace` to — was it generated by `flutter create`?'
    )
  }
  // The inserted lines use the file's OWN line ending. Writing `\n` into a CRLF
  // file would leave it mixed, which git reports as a whole-file change on the
  // next checkout and which no reader would expect from a two-line insertion.
  const newline = contents.includes('\r\n') ? '\r\n' : '\n'

  return contents.replace(
    ENVIRONMENT_BLOCK,
    block => `${block}${newline}resolution: workspace${newline}`
  )
}
