import type { Tree } from '@nx/devkit'

/**
 * The workspace-root pubspec that owns every member's dependency resolution.
 *
 * @remarks
 * Also the sentinel every generated CI guard tests for, the way `go.mod` is for
 * Go — its presence is what tells the pipeline this workspace has Dart in it.
 */
export const ROOT_PUBSPEC = 'pubspec.yaml'

/**
 * The workspace-root analyser config every member includes.
 *
 * @remarks
 * Central lint configuration: each project's own file is a one-line relative
 * `include:` of this one, so rules are changed in a single place.
 */
export const ROOT_ANALYSIS_OPTIONS = 'analysis_options.yaml'

/**
 * The lowest Dart SDK that supports pub workspaces.
 *
 * @remarks
 * Workspaces landed in Dart 3.6.0; `pub` rejects a workspace whose members
 * declare anything lower. Pinned as a floor (`^3.6.0`), not an exact version,
 * so a workspace keeps working on newer SDKs.
 */
export const WORKSPACE_SDK_CONSTRAINT = '^3.6.0'

/** Matches the `workspace:` block and its indented `- path` entries. */
const WORKSPACE_BLOCK = /^workspace:\n(?:[ \t]*-[ \t]*\S+\n)*/m

/**
 * The root `pubspec.yaml` for a brand-new Flutter-enabled workspace.
 *
 * @remarks
 * This is the Flutter half of mnci's root-manifest model — the direct
 * analogue of the root `package.json` for TS, `requirements-dev.txt` for
 * Python and `go.mod` for Go. It is what makes dependencies *central*: with
 * every project listed under `workspace:` and carrying
 * `resolution: workspace`, a single `flutter pub get` at the root resolves
 * the whole graph into **one** `pubspec.lock` and **one**
 * `.dart_tool/package_config.json`, and `pub` deletes any per-package copies.
 *
 * The payoff that matters day to day: a member depending on another member
 * declares a plain version constraint (`core: ^0.0.1`) with **no `path:`** —
 * pub resolves it to the local package because it is in the workspace.
 * Verified empirically against Flutter 3.44.8 / Dart 3.12.2, including the
 * negative case (the depended-on package does not exist on pub.dev at all,
 * so resolution could only have been local).
 *
 * `name` must be a Dart identifier and `publish_to: none` keeps the root
 * itself unpublishable — it exists only to own the resolution, never to ship.
 *
 * @param workspaceName - The Dart-safe workspace package name.
 * @returns The pubspec.yaml text.
 * @throws Never - pure string construction.
 * @typeParam None - this function has no generic type parameters.
 */
export function rootPubspec(workspaceName: string): string {
  return `# Generated by MoNecromanCI — the Dart pub workspace root.
#
# Every Flutter/Dart project mnci adds is listed under \`workspace:\` below and
# carries \`resolution: workspace\` in its own pubspec, so ONE \`flutter pub get\`
# here resolves them all into a single root pubspec.lock. A member depending on
# another member uses a plain version constraint — no \`path:\` needed.
name: ${workspaceName}
publish_to: none

environment:
  sdk: ${WORKSPACE_SDK_CONSTRAINT}

workspace:
`
}

/**
 * The workspace-root `analysis_options.yaml` every member inherits.
 *
 * @remarks
 * Central lint configuration, the Dart-native way: one file at the root that
 * members pull in with a relative `include:`, so a rule change lands in one
 * place instead of once per project. `flutter_lints` is Flutter's own
 * recommended rule set (a superset of `package:lints/recommended.yaml`).
 *
 * @param None - this function takes no parameters.
 * @returns The analysis_options.yaml text.
 * @throws Never - pure string construction.
 * @typeParam None - this function has no generic type parameters.
 */
export function rootAnalysisOptions(): string {
  return `# Generated by MoNecromanCI — the one analyser config for every Dart project.
#
# Each project's own analysis_options.yaml is a single \`include:\` pointing back
# here, so lint rules are configured centrally. Add project-local overrides in
# that file, not by copying this one.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
`
}

/**
 * A member project's `analysis_options.yaml`: an include of the root's.
 *
 * @remarks
 * Replaces the standalone config `flutter create` writes (which pulls in
 * `package:flutter_lints/flutter.yaml` directly), so every project resolves
 * its rules through the workspace root instead of carrying its own copy.
 *
 * @param depth - How many directories the project sits below the root
 * (`apps/<name>` is 2), used to build the relative path.
 * @returns The analysis_options.yaml text.
 * @throws Never - pure string construction.
 * @typeParam None - this function has no generic type parameters.
 */
export function memberAnalysisOptions(depth: number): string {
  const up = '../'.repeat(depth)
  return `# Generated by MoNecromanCI — lint rules are configured at the workspace root.
include: ${up}analysis_options.yaml
`
}

/**
 * Ensures the workspace-root pubspec and analyser config exist.
 *
 * @remarks
 * Idempotent, and deliberately so: it runs on *every* Flutter add, but only
 * writes when the file is absent, so a user's own edits to either root file
 * (extra `dev_dependencies`, custom lint rules) survive every later add.
 * Mirrors `ensureGoModule` in the CLI's `add/go.ts`, which guards the root
 * `go.mod` the same way.
 *
 * @param tree - The Nx virtual file system.
 * @param workspaceName - The Dart-safe workspace package name.
 * @returns Nothing.
 * @throws Never - pure Tree writes.
 * @typeParam None - this function has no generic type parameters.
 */
export function ensureWorkspaceRoot(tree: Tree, workspaceName: string): void {
  if (!tree.exists(ROOT_PUBSPEC)) {
    tree.write(ROOT_PUBSPEC, rootPubspec(workspaceName))
  }
  if (!tree.exists(ROOT_ANALYSIS_OPTIONS)) {
    tree.write(ROOT_ANALYSIS_OPTIONS, rootAnalysisOptions())
  }
}

/**
 * Adds a project directory to the root pubspec's `workspace:` list.
 *
 * @remarks
 * Idempotent — a directory already listed is left alone, so repeat adds (and
 * re-runs after a failure) never duplicate an entry. Entries are kept sorted
 * so the file stays diff-friendly as projects accumulate.
 *
 * A member that is not listed here still has a valid pubspec, but `pub`
 * resolves it *standalone* — it silently gets its own lockfile and drops out
 * of the shared resolution. That failure is quiet, which is why this is
 * written by the generator rather than left to the user.
 *
 * @param tree - The Nx virtual file system.
 * @param projectRoot - The workspace-relative project directory.
 * @returns Nothing.
 * @throws Error when the root pubspec has no `workspace:` block.
 * @typeParam None - this function has no generic type parameters.
 */
export function addWorkspaceMember(tree: Tree, projectRoot: string): void {
  const contents = tree.read(ROOT_PUBSPEC, 'utf8') ?? ''
  const block = WORKSPACE_BLOCK.exec(contents)
  if (!block) {
    throw new Error(
      `Root ${ROOT_PUBSPEC} has no \`workspace:\` block — it was not written by mnci, so members cannot be registered automatically.`
    )
  }
  const existing = block[0]
    .split('\n')
    .slice(1)
    .map(line => line.replace(/^[ \t]*-[ \t]*/, '').trim())
    .filter(Boolean)
  if (existing.includes(projectRoot)) {
    return
  }
  // `sort` rather than `toSorted`: this package compiles against the es2021 lib
  // (matching @mnci/nx-python-pip), where `toSorted` does not exist. Sorting in
  // place is safe regardless — the spread above already made a fresh array.
  // eslint-disable-next-line unicorn/no-array-sort -- es2021 lib has no toSorted
  const members = [...existing, projectRoot].sort((a, b) => a.localeCompare(b))
  const rebuilt = `workspace:\n${members.map(member => `  - ${member}\n`).join('')}`
  // Function replacement so a `$` in a project path cannot be read as a
  // capture-group reference.
  tree.write(
    ROOT_PUBSPEC,
    contents.replace(WORKSPACE_BLOCK, () => rebuilt)
  )
}
