import { join } from 'node:path'
import { runShell } from '../../nx'
import { fileExists, toJson, writeFileEnsured } from '../../util/fsx'
import { ensureAdmZip } from './shared'

/**
 * Fails fast, with an install hint, when Python is not on the PATH.
 *
 * @remarks
 * Unlike the old `@nxlv/python`-based toolchain, nothing else is required —
 * every other tool (`build`, `twine`, `ruff`, `pytest`) is a plain pip package
 * declared in {@link PYTHON_REQUIREMENTS_DEV} and invoked via `python3 -m`, so
 * there is no second CLI (no `uv`) to preflight.
 *
 * @param workspaceRoot - Absolute path to the workspace (cwd for the probe).
 * @returns Nothing.
 * @throws Error when neither `python3` nor `python` can be run.
 * @typeParam None - this function has no generic type parameters.
 */
function ensurePython (workspaceRoot: string): void {
  const hasPython = runShell('python3', ['--version'], workspaceRoot) === 0 || runShell('python', ['--version'], workspaceRoot) === 0
  if (!hasPython) {
    throw new Error('Python not found. Install Python 3.9+ first: https://www.python.org/downloads/')
  }
}

/**
 * The fixed toolchain every Python project shares, written once to the
 * workspace root as `requirements-dev.txt`.
 *
 * @remarks
 * Ruff and pytest are the industry standard (and were the `@nxlv/python`
 * defaults); `build` and `twine` are the standard PyPA build/publish
 * frontends. No lock file — plain pip has none, matching the company's
 * standard toolchain (no uv, no Poetry).
 */
export const PYTHON_REQUIREMENTS_DEV = `build
twine
ruff
pytest
`

/**
 * The vendoring-aware build helper written once to `tools/python-build.js`.
 *
 * @remarks
 * Plain pip has no `bundleLocalDependencies` equivalent, so a project that
 * imports a workspace-internal Python library needs its own vendoring step: a
 * hand-added `[tool.mnci2] vendor = ["<lib>"]` table in the consuming
 * project's `pyproject.toml` (the pip-world counterpart of hand-wiring a
 * `dependencies = [...]` entry — mnci2 performs no automatic cross-project
 * dependency wiring for any kind) tells this script which sibling internal
 * libraries (always at `libs/<name>`, mnci2's fixed internal-lib location) to
 * copy into a staged copy of the project before running `python -m build` —
 * so the resulting wheel contains the vendored module as a real top-level
 * package, exactly as if it had been written there directly. Projects with no
 * `vendor` entry build straight from their own directory, no staging.
 */
export const PYTHON_BUILD_SCRIPT = `#!/usr/bin/env node
// Generated by MoNecromanCI v2. Builds a Python project's wheel/sdist via
// \`python -m build\`. When the project's pyproject.toml declares
// [tool.mnci2] vendor = ["some-internal-lib"], the named libs/<name> module is
// copied into a staged copy of the project first, so the built wheel bundles
// it as a real top-level package (plain pip has no bundled-local-dependency
// feature of its own).
'use strict'

const { execFileSync } = require('node:child_process')
const { cpSync, mkdtempSync, readFileSync, rmSync, writeFileSync } = require('node:fs')
const { tmpdir } = require('node:os')
const { join } = require('node:path')

const projectRoot = process.argv[2]
if (!projectRoot) {
  console.error('Usage: node tools/python-build.js <project-root>')
  process.exit(1)
}

const outDir = join(process.cwd(), projectRoot, 'dist')
const pyproject = readFileSync(join(projectRoot, 'pyproject.toml'), 'utf-8')
const vendorMatch = /^\\s*vendor\\s*=\\s*\\[([^\\]]*)\\]/m.exec(pyproject)
const vendorNames = vendorMatch
  ? vendorMatch[1].split(',').map((entry) => entry.trim().replace(/^["']|["']$/g, '')).filter(Boolean)
  : []

if (vendorNames.length === 0) {
  execFileSync('python3', ['-m', 'build', '--outdir', outDir, projectRoot], { stdio: 'inherit' })
  process.exit(0)
}

const stagingRoot = mkdtempSync(join(tmpdir(), 'mnci2-python-build-'))
cpSync(projectRoot, stagingRoot, { recursive: true })

const moduleDirs = vendorNames.map((name) => name.replaceAll('-', '_'))
for (const [index, name] of vendorNames.entries()) {
  cpSync(join('libs', name, moduleDirs[index]), join(stagingRoot, moduleDirs[index]), { recursive: true })
}

const stagedPyprojectPath = join(stagingRoot, 'pyproject.toml')
const stagedPyproject = readFileSync(stagedPyprojectPath, 'utf-8')
const patched = stagedPyproject.replace(/^(\\s*packages\\s*=\\s*)\\[([^\\]]*)\\]/m, (_match, prefix, existing) => {
  const names = existing.split(',').map((entry) => entry.trim().replace(/^["']|["']$/g, '')).filter(Boolean)
  const merged = [...new Set([...names, ...moduleDirs])]
  return \`\${prefix}[\${merged.map((name) => \`"\${name}"\`).join(', ')}]\`
})
writeFileSync(stagedPyprojectPath, patched)

try {
  execFileSync('python3', ['-m', 'build', '--outdir', outDir, stagingRoot], { stdio: 'inherit' })
} finally {
  rmSync(stagingRoot, { recursive: true, force: true })
}
`

/**
 * The hand-written `VersionActions` implementation written once to
 * `tools/python-version-actions.js`.
 *
 * @remarks
 * Registered per-project (see {@link addPythonLib}, the only Python kind that
 * gets a `release.version.versionActions` override) so `nx release` versions
 * publishable Python libs the same way it versions npm packages — from
 * conventional commits — without `@nxlv/python`. Reads and writes the
 * `version = "..."` line under `pyproject.toml`'s `[project]`
 * table with a regex, safe because mnci2 authors that file's exact shape
 * itself (same reasoning the plain-JSON `readJson`/`toJson` helpers rely on
 * elsewhere, applied to the one line of TOML this needs — no TOML dependency
 * pulled in for it). Internal-lib dependencies are vendored (bundled into the
 * wheel), not registry references, so dependency version resolution/update
 * are no-ops — the same branch `@nxlv/python`'s own reference implementation
 * takes for bundled dependencies.
 */
export const PYTHON_VERSION_ACTIONS_SCRIPT = `// Generated by MoNecromanCI v2. Hand-written Nx release VersionActions for
// pip-native Python packages (no uv, no Poetry) — reads/writes the
// \`version = "..."\` line under pyproject.toml's [project] table.
'use strict'

const { readFileSync } = require('node:fs')
const { execFileSync } = require('node:child_process')
const { join } = require('node:path')
const { VersionActions } = require('nx/src/command-line/release/version/version-actions')

const VERSION_LINE = /^version\\s*=\\s*"([^"]+)"/m

class PythonVersionActions extends VersionActions {
  validManifestFilenames = ['pyproject.toml']

  async readCurrentVersionFromSourceManifest (tree) {
    const manifestPath = join(this.projectGraphNode.data.root, 'pyproject.toml')
    const content = tree.read(manifestPath, 'utf-8')
    if (content === null) {
      return null
    }
    const match = VERSION_LINE.exec(content)
    if (!match) {
      throw new Error(\`Could not find a "version = ..." line under [project] in \${manifestPath}\`)
    }
    return { currentVersion: match[1], manifestPath }
  }

  async readCurrentVersionFromRegistry (_tree, _currentVersionResolverMetadata) {
    const name = this.projectGraphNode.name
    try {
      const output = execFileSync('python3', ['-m', 'pip', 'index', 'versions', name], { encoding: 'utf-8', stdio: ['ignore', 'pipe', 'ignore'] })
      const match = /Available versions:\\s*([^\\s,]+)/.exec(output)
      return { currentVersion: match ? match[1] : null, logText: 'from pip index versions' }
    } catch {
      return { currentVersion: null, logText: 'package not found on registry' }
    }
  }

  async readCurrentVersionOfDependency (_tree, _projectGraph, _dependencyProjectName) {
    // Internal-lib dependencies are vendored (copied into the wheel at build
    // time), not registry-referenced, so there is no separate version to track.
    return { currentVersion: null, dependencyCollection: null }
  }

  async updateProjectVersion (tree, newVersion) {
    const manifestPath = join(this.projectGraphNode.data.root, 'pyproject.toml')
    const content = tree.read(manifestPath, 'utf-8')
    const updated = content.replace(VERSION_LINE, \`version = "\${newVersion}"\`)
    tree.write(manifestPath, updated)
    return [\`Updated \${manifestPath} to version \${newVersion}\`]
  }

  async updateProjectDependencies (_tree, _projectGraph, _dependenciesToUpdate) {
    // Same reasoning as readCurrentVersionOfDependency: vendored, not registry deps.
    return []
  }
}

module.exports = PythonVersionActions
`

/**
 * Idempotently writes the shared pip-native Python tooling into the workspace.
 *
 * @remarks
 * Lazy, like {@link ensureAdmZip}: written on the first Python `add` of any
 * kind, not unconditionally by `mnci2 new` — a pure-JS/TS workspace never
 * gains these files. `tools/python-build.js` and `tools/python-version-actions.js`
 * are written verbatim (no per-project templating); `requirements-dev.txt`
 * only when absent, so a user's own edits to it (extra dev tools) survive
 * repeat `add` calls.
 *
 * @param workspaceRoot - Absolute path to the workspace.
 * @returns Nothing.
 * @throws Propagates any Node.js `fs` error raised while writing.
 * @typeParam None - this function has no generic type parameters.
 */
function ensurePythonTooling (workspaceRoot: string): void {
  writeFileEnsured(join(workspaceRoot, 'tools', 'python-build.js'), PYTHON_BUILD_SCRIPT)
  writeFileEnsured(join(workspaceRoot, 'tools', 'python-version-actions.js'), PYTHON_VERSION_ACTIONS_SCRIPT)
  const requirementsDevPath = join(workspaceRoot, 'requirements-dev.txt')
  if (!fileExists(requirementsDevPath)) {
    writeFileEnsured(requirementsDevPath, PYTHON_REQUIREMENTS_DEV)
  }
}

/**
 * A Python project's module directory name, derived from its Nx project name.
 *
 * @remarks
 * Python identifiers cannot contain hyphens, so `my-svc` becomes `my_svc` —
 * the same convention `@nxlv/python` used, kept for continuity.
 *
 * @param name - The Nx project name (already validated).
 * @returns The module directory's basename.
 * @throws Never - pure string mapping.
 * @typeParam None - this function has no generic type parameters.
 */
function pythonModuleDirectory (name: string): string {
  return name.replaceAll('-', '_')
}

/**
 * The `pyproject.toml` written for a buildable Python project (app or lib).
 *
 * @remarks
 * `hatchling` is the PEP 517 backend (unchanged from the `@nxlv/python`-era
 * choice); `[tool.hatch.build.targets.wheel] packages` is explicit (not
 * hatchling's own auto-detection) because {@link PYTHON_BUILD_SCRIPT} patches
 * this exact list when vendoring an internal lib's module into the wheel.
 * `[project.dependencies]` starts empty — a project that needs a real
 * external PyPI dependency (or, per {@link PYTHON_BUILD_SCRIPT}'s remarks, a
 * vendored internal one via `[tool.mnci2] vendor = [...]`) is wired by hand
 * after generation, same as every other cross-project dependency mnci2 leaves
 * to the user.
 *
 * @param name - The project name (already validated).
 * @param moduleDirectory - The project's module directory basename.
 * @returns The `pyproject.toml` contents.
 * @throws Never - pure string build.
 * @typeParam None - this function has no generic type parameters.
 */
function pythonPyprojectToml (name: string, moduleDirectory: string): string {
  return `[project]
name = "${name}"
version = "1.0.0"
description = ""
requires-python = ">=3.9"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["${moduleDirectory}"]

[tool.pytest.ini_options]
testpaths = ["tests"]
`
}

/**
 * A sample pure function written into a generated Python project's module.
 *
 * @remarks
 * Gives every Python kind a genuinely testable unit out of the box, mirroring
 * the JS side's generator-provided sample.
 *
 * @param moduleDirectory - The project's module directory basename.
 * @returns The `<module>/__init__.py` contents.
 * @throws Never - pure string build.
 * @typeParam None - this function has no generic type parameters.
 */
function pythonSampleModule (moduleDirectory: string): string {
  return `def hello() -> str:
    return "hello from ${moduleDirectory}"
`
}

/**
 * The sample pytest proving a generated Python project's `test` target runs.
 *
 * @param moduleDirectory - The project's module directory basename.
 * @returns The `tests/test_<module>.py` contents.
 * @throws Never - pure string build.
 * @typeParam None - this function has no generic type parameters.
 */
function pythonSampleTest (moduleDirectory: string): string {
  return `from ${moduleDirectory} import hello


def test_hello() -> None:
    assert hello() == "hello from ${moduleDirectory}"
`
}

/** The `lint` target shared by every Python kind: ruff, no project deps needed. */
function pythonLintTarget (root: string): Record<string, unknown> {
  return { executor: 'nx:run-commands', options: { command: 'python3 -m ruff check .', cwd: root } }
}

/**
 * The `test` target shared by every buildable Python kind (app/lib).
 *
 * @remarks
 * `pip install --quiet -e .` first, so the project's own declared
 * dependencies (and the project itself) are importable for pytest — no
 * uv-managed venv auto-sync to rely on anymore, so this is explicit. Function
 * apps (never built to a wheel) use {@link pythonFunctionAppTestTarget}
 * instead, which skips the install.
 */
function pythonTestTarget (root: string): Record<string, unknown> {
  return { executor: 'nx:run-commands', options: { command: 'python3 -m pip install --quiet -e . && python3 -m pytest', cwd: root } }
}

/** The `test` target for a Python Azure Function: no `pyproject.toml`/install, just pytest. */
function pythonFunctionAppTestTarget (root: string): Record<string, unknown> {
  return { executor: 'nx:run-commands', options: { command: 'python3 -m pytest', cwd: root } }
}

/**
 * The `build` target shared by every buildable Python kind (app/lib).
 *
 * @remarks
 * Delegates to {@link PYTHON_BUILD_SCRIPT} (`tools/python-build.js`), which
 * handles both the plain case and the vendoring case identically from the
 * caller's point of view.
 *
 * @param root - Workspace-relative project directory.
 * @returns The nx:run-commands target object.
 * @throws Never - pure object construction.
 * @typeParam None - this function has no generic type parameters.
 */
function pythonBuildTarget (root: string): Record<string, unknown> {
  return {
    executor: 'nx:run-commands',
    options:  { command: `node tools/python-build.js ${root}` },
    // eslint-disable-next-line unicorn/no-incorrect-template-string-interpolation -- {workspaceRoot} is an Nx output token
    outputs:  [`{workspaceRoot}/${root}/dist`],
  }
}

/**
 * The `nx-release-publish` target for a publishable Python library.
 *
 * @remarks
 * `--skip-existing` mirrors npm's own idempotent-publish behaviour (Nx's
 * default `@nx/js:release-publish` also tolerates a version already on the
 * registry), so a re-run after a partial release failure does not hard-error
 * on the packages that already made it. Credentials
 * (`TWINE_USERNAME`/`TWINE_PASSWORD`/`TWINE_REPOSITORY_URL`) are read from the
 * environment by twine itself — set by CI (see `overlay.ts`'s
 * `azurePipelinesYaml`), never written to disk here.
 *
 * `nx release publish --dry-run` (the workspace's `release:preview` script)
 * appends a literal `--dryRun=true` to whatever command a plain
 * `nx:run-commands` `nx-release-publish` target runs — unlike
 * `@nx/js:release-publish`, a real executor that parses and honours the flag
 * `nx:run-commands` has no such awareness (verified empirically: the
 * unguarded command hard-fails, twine rejecting the unrecognized argument).
 * The `node -e` wrapper below detects that flag and prints a preview instead
 * of shelling out to twine for real.
 *
 * @param root - Workspace-relative project directory.
 * @returns The nx:run-commands target object.
 * @throws Never - pure object construction.
 * @typeParam None - this function has no generic type parameters.
 */
function pythonReleasePublishTarget (root: string): Record<string, unknown> {
  // The trailing `--` matters: nx appends --dryRun=true straight onto this
  // command string, and without `--` node itself tries (and fails) to parse
  // it as a node CLI flag rather than handing it to the script as argv.
  const command = `node -e "const isDryRun=process.argv.slice(1).some((a)=>a.startsWith('--dryRun'));if(isDryRun){console.log('[dry-run] would run: python3 -m twine upload --skip-existing dist/*');process.exit(0)}process.exit(require('node:child_process').spawnSync('python3',['-m','twine','upload','--skip-existing','dist/*'],{stdio:'inherit'}).status??1)" --`
  return {
    executor:  'nx:run-commands',
    dependsOn: ['build'],
    options:   { command, cwd: root },
  }
}

/**
 * The `package` target for a Python app: zip its built wheel into the drop.
 *
 * @remarks
 * Zips `apps/<name>/dist` (the {@link pythonBuildTarget} wheel + sdist) into
 * `dist/drop/python-app-<name>.zip` — basename exactly `python-app-<name>`,
 * the string CI turns into the per-app build tag. `dependsOn: build`
 * guarantees the wheel exists; same cross-platform `adm-zip` one-liner used
 * throughout `add`.
 *
 * @param name - The Python app's project name.
 * @returns The nx:run-commands target object.
 * @throws Never - pure object construction.
 * @typeParam None - this function has no generic type parameters.
 */
function pythonAppPackageTarget (name: string): Record<string, unknown> {
  const zip = `dist/drop/python-app-${name}.zip`
  const command = `node -e "const fs=require('node:fs');fs.mkdirSync('dist/drop',{recursive:true});const A=require('adm-zip');const z=new A();z.addLocalFolder('apps/${name}/dist');z.writeZip('${zip}')"`
  return {
    executor:  'nx:run-commands',
    dependsOn: ['build'],
    // eslint-disable-next-line unicorn/no-incorrect-template-string-interpolation -- {workspaceRoot} is an Nx output token
    outputs:   [`{workspaceRoot}/${zip}`],
    options:   { command },
  }
}

/**
 * The `package` target for a Python Azure Function: zip the deploy folder.
 *
 * @remarks
 * An Azure Functions Python app is deployed as **source** (the host installs
 * `requirements.txt` and runs `function_app.py`), not as a wheel — so this
 * zips `function_app.py` + `host.json` + `requirements.txt` + the module
 * package into `dist/drop/python-function-app-<name>.zip`. Basename exactly
 * `python-function-app-<name>` (the CI build tag). No `build` dependency (the
 * artifact is source), same `adm-zip` one-liner.
 *
 * @param name - The function app's project name.
 * @param moduleDirectory - The app's Python module directory basename.
 * @returns The nx:run-commands target object.
 * @throws Never - pure object construction.
 * @typeParam None - this function has no generic type parameters.
 */
function pythonFunctionAppPackageTarget (name: string, moduleDirectory: string): Record<string, unknown> {
  const zip = `dist/drop/python-function-app-${name}.zip`
  const root = `apps/${name}`
  const command = `node -e "const fs=require('node:fs');fs.mkdirSync('dist/drop',{recursive:true});const A=require('adm-zip');const z=new A();z.addLocalFile('${root}/function_app.py');z.addLocalFile('${root}/host.json');z.addLocalFile('${root}/requirements.txt');z.addLocalFolder('${root}/${moduleDirectory}','${moduleDirectory}');z.writeZip('${zip}')"`
  return {
    executor: 'nx:run-commands',
    // eslint-disable-next-line unicorn/no-incorrect-template-string-interpolation -- {workspaceRoot} is an Nx output token
    outputs:  [`{workspaceRoot}/${zip}`],
    options:  { command },
  }
}

/**
 * The Azure Functions v2 entry written into a generated Python function app.
 *
 * @remarks
 * The Python v2 programming model: a module-level `func.FunctionApp()` with
 * decorated routes. The handler is thin — the testable logic lives in the
 * module's `greeting.py` (imported here), so pytest needs no `azure-functions`
 * install. Anonymous auth keeps the sample runnable locally with `func start`.
 *
 * @param moduleDirectory - The app's Python module directory (import root).
 * @returns The `function_app.py` contents.
 * @throws Never - pure string build.
 * @typeParam None - this function has no generic type parameters.
 */
export function pythonFunctionAppMain (moduleDirectory: string): string {
  return `import azure.functions as func

from ${moduleDirectory}.greeting import build_greeting

app = func.FunctionApp(http_auth_level=func.AuthLevel.ANONYMOUS)


@app.route(route="hello")
def hello(req: func.HttpRequest) -> func.HttpResponse:
    name = req.params.get("name", "world")
    return func.HttpResponse(build_greeting(name))
`
}

/**
 * The `host.json` written into a generated Python function app.
 *
 * @remarks
 * The v4 extension bundle is what the Functions host uses to resolve bindings;
 * `version: 2.0` is the runtime schema. Deliberately minimal.
 */
export const PYTHON_FUNCTION_APP_HOST_JSON = `{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[4.*, 5.0.0)"
  }
}
`

/**
 * The `requirements.txt` written into a generated Python function app.
 *
 * @remarks
 * Azure's Python worker installs these at deploy time (Oryx build). Only the
 * SDK is needed for the sample; app deps are added here as the app grows.
 */
export const PYTHON_FUNCTION_APP_REQUIREMENTS = `azure-functions
`

/**
 * A sample pure helper written into a Python function app's module.
 *
 * @remarks
 * Gives the app a genuinely testable unit (the HTTP handler would need the
 * Functions runtime), so pytest has a real passing test out of the box.
 */
export const PYTHON_FUNCTION_APP_GREETING = `def build_greeting(name: str) -> str:
    """Build the greeting returned by the sample HTTP function."""
    return "Hello, " + name + "!"
`

/**
 * The sample pytest proving the Python function app's test target runs.
 *
 * @remarks
 * Imports only the pure helper (no `azure-functions`), so it passes on a bare
 * workspace with plain `pytest` — no install step needed.
 *
 * @param moduleDirectory - The app's Python module directory (import root).
 * @returns The `tests/test_greeting.py` contents.
 * @throws Never - pure string build.
 * @typeParam None - this function has no generic type parameters.
 */
export function pythonFunctionAppGreetingTest (moduleDirectory: string): string {
  return `from ${moduleDirectory}.greeting import build_greeting


def test_build_greeting() -> None:
    assert build_greeting("world") == "Hello, world!"
`
}

/**
 * Writes a hand-authored `project.json` for a Python project.
 *
 * @remarks
 * There is no generator left to write one — mnci2 owns the whole shape,
 * mirroring how the old hand-built function app worked before it had a real
 * generator (except this time there is none to eventually lean on).
 *
 * `release` is only set by {@link addPythonLib}: a project-level
 * `release.version.versionActions` wins over the workspace release group's
 * (see `overlay.ts`'s `RELEASE_CONFIG` remarks for why the group itself stays
 * generic) — the same mechanism `@nxlv/python`'s own `--publishable` flag
 * used to stamp its versioning hook onto just the one project.
 *
 * @param root - Absolute path to the project's directory.
 * @param name - The Nx project name.
 * @param projectType - `application` (apps) or `library` (packages/libs).
 * @param targets - The project's Nx targets.
 * @param release - Optional per-project `release` config override.
 * @returns Nothing.
 * @throws Propagates any Node.js `fs` error raised while writing.
 * @typeParam None - this function has no generic type parameters.
 */
function writePythonProjectJson (root: string, name: string, projectType: 'application' | 'library', targets: Record<string, unknown>, release?: Record<string, unknown>): void {
  writeFileEnsured(join(root, 'project.json'), toJson({ name, projectType, sourceRoot: root, targets, ...(release && { release }) }))
}

/**
 * Adds a Python app: hand-authored pyproject.toml + project.json, no plugin.
 *
 * @remarks
 * The build target emits a wheel to `apps/<name>/dist`;
 * {@link pythonAppPackageTarget} zips that into the drop under the exact name
 * CI turns into a build tag.
 *
 * @param workspaceRoot - Absolute path to the workspace.
 * @param name - The project name (already validated).
 * @returns Nothing.
 * @throws Error when Python is missing.
 * @typeParam None - this function has no generic type parameters.
 */
export function addPythonApp (workspaceRoot: string, name: string): void {
  ensurePython(workspaceRoot)
  ensurePythonTooling(workspaceRoot)
  ensureAdmZip(workspaceRoot)

  const root = `apps/${name}`
  const absoluteRoot = join(workspaceRoot, root)
  const moduleDirectory = pythonModuleDirectory(name)
  writeFileEnsured(join(absoluteRoot, 'pyproject.toml'), pythonPyprojectToml(name, moduleDirectory))
  writeFileEnsured(join(absoluteRoot, moduleDirectory, '__init__.py'), pythonSampleModule(moduleDirectory))
  writeFileEnsured(join(absoluteRoot, 'tests', `test_${moduleDirectory}.py`), pythonSampleTest(moduleDirectory))
  writePythonProjectJson(absoluteRoot, name, 'application', {
    lint:    pythonLintTarget(root),
    test:    pythonTestTarget(root),
    build:   pythonBuildTarget(root),
    package: pythonAppPackageTarget(name),
  })
}

/**
 * Adds a Python Azure Function: hand-authored project.json + the Azure Functions v2 shape.
 *
 * @remarks
 * No `pyproject.toml`/wheel build — the deployable is the source zip
 * ({@link pythonFunctionAppPackageTarget}), so `func` CLI is not needed and
 * there is no `build` target at all.
 *
 * @param workspaceRoot - Absolute path to the workspace.
 * @param name - The project name (already validated).
 * @returns Nothing.
 * @throws Error when Python is missing.
 * @typeParam None - this function has no generic type parameters.
 */
export function addPythonFunctionApp (workspaceRoot: string, name: string): void {
  ensurePython(workspaceRoot)
  ensurePythonTooling(workspaceRoot)
  ensureAdmZip(workspaceRoot)

  const root = `apps/${name}`
  const absoluteRoot = join(workspaceRoot, root)
  const moduleDirectory = pythonModuleDirectory(name)
  writeFileEnsured(join(absoluteRoot, 'function_app.py'), pythonFunctionAppMain(moduleDirectory))
  writeFileEnsured(join(absoluteRoot, 'host.json'), PYTHON_FUNCTION_APP_HOST_JSON)
  writeFileEnsured(join(absoluteRoot, 'requirements.txt'), PYTHON_FUNCTION_APP_REQUIREMENTS)
  writeFileEnsured(join(absoluteRoot, moduleDirectory, 'greeting.py'), PYTHON_FUNCTION_APP_GREETING)
  writeFileEnsured(join(absoluteRoot, 'tests', 'test_greeting.py'), pythonFunctionAppGreetingTest(moduleDirectory))
  writePythonProjectJson(absoluteRoot, name, 'application', {
    lint:    pythonLintTarget(root),
    test:    pythonFunctionAppTestTarget(root),
    package: pythonFunctionAppPackageTarget(name, moduleDirectory),
  })
}

/**
 * Adds a publishable Python library under `python-packages/`.
 *
 * @remarks
 * `nx-release-publish` (twine) is a hand-authored target, not a plugin hook —
 * so the shared `nx release` (scoped to `python-packages/*` — see
 * `overlay.ts`'s `RELEASE_CONFIG`) versions, tags and publishes it via
 * {@link pythonReleasePublishTarget}. `release.version.versionActions` is set
 * here, on the project itself (not the workspace-level release config), so
 * `nx release` reads/writes this project's `pyproject.toml` via the
 * hand-written `PythonVersionActions` instead of npm's default.
 *
 * @param workspaceRoot - Absolute path to the workspace.
 * @param name - The project name (already validated).
 * @returns Nothing.
 * @throws Error when Python is missing.
 * @typeParam None - this function has no generic type parameters.
 */
export function addPythonLib (workspaceRoot: string, name: string): void {
  ensurePython(workspaceRoot)
  ensurePythonTooling(workspaceRoot)

  const root = `python-packages/${name}`
  const absoluteRoot = join(workspaceRoot, root)
  const moduleDirectory = pythonModuleDirectory(name)
  writeFileEnsured(join(absoluteRoot, 'pyproject.toml'), pythonPyprojectToml(name, moduleDirectory))
  writeFileEnsured(join(absoluteRoot, moduleDirectory, '__init__.py'), pythonSampleModule(moduleDirectory))
  writeFileEnsured(join(absoluteRoot, 'tests', `test_${moduleDirectory}.py`), pythonSampleTest(moduleDirectory))
  writePythonProjectJson(absoluteRoot, name, 'library', {
    lint:                 pythonLintTarget(root),
    test:                 pythonTestTarget(root),
    build:                pythonBuildTarget(root),
    'nx-release-publish': pythonReleasePublishTarget(root),
  }, { version: { versionActions: 'tools/python-version-actions.js' } })
}

/**
 * Adds a private Python library under `libs/`.
 *
 * @remarks
 * Not publishable (no `nx-release-publish` target, and not under
 * `python-packages/*`), so it is structurally never released. Consumers
 * vendor its module directly into their own wheel at build time (see
 * {@link PYTHON_BUILD_SCRIPT}) by hand-adding a `[tool.mnci2] vendor = [...]`
 * entry to their own `pyproject.toml` — the pip-world equivalent of the old
 * `bundleLocalDependencies` plugin option.
 *
 * @param workspaceRoot - Absolute path to the workspace.
 * @param name - The project name (already validated).
 * @returns Nothing.
 * @throws Error when Python is missing.
 * @typeParam None - this function has no generic type parameters.
 */
export function addPythonInternalLib (workspaceRoot: string, name: string): void {
  ensurePython(workspaceRoot)
  ensurePythonTooling(workspaceRoot)

  const root = `libs/${name}`
  const absoluteRoot = join(workspaceRoot, root)
  const moduleDirectory = pythonModuleDirectory(name)
  writeFileEnsured(join(absoluteRoot, 'pyproject.toml'), pythonPyprojectToml(name, moduleDirectory))
  writeFileEnsured(join(absoluteRoot, moduleDirectory, '__init__.py'), pythonSampleModule(moduleDirectory))
  writeFileEnsured(join(absoluteRoot, 'tests', `test_${moduleDirectory}.py`), pythonSampleTest(moduleDirectory))
  writePythonProjectJson(absoluteRoot, name, 'library', {
    lint: pythonLintTarget(root),
    test: pythonTestTarget(root),
  })
}
